- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/Login/LoginContainer.tsx
- src/services/auth/index.tsx
Found an edge case while doing testing. Let's say there's an example where a customer comes in and buys everything, at the Purchase screen, the "Next Customer" button will not be within the screen as the purchase list is too long. Hence the adding of the paddingBottom to all ctaButtons instead, rather than just for one.
Other stuff in this PR:
- There was some error reported by Policy, so I fixed it
- Adding a console log for the authenticated for the time being to monitor the bug ZY raised
> Fix issue where user cannot select "Next Customer" at the purchase screen

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/navigation/StackNavigator/CollectCustomerDetailsScreen.tsx
There were reports of people who have not redeemed anything seeing that they don't have any quota left. I noticed this firsthand, and it occurs when a batch (household) of IDs were being scanned.
I managed to reproduce it several times when combined with a throttled network and on slower devices. For example, given 2 IDs, A and B, by scanning in quick succession, there are times when the quota of B is recorded when the user thinks A's quota is being recorded. So when scanning B, it correctly shows that B does not have quota left. If the user scans A again, he'll notice that there's quota available for A.
The issue stems from the camera on the scanning ID screen not being turned off properly after an ID was identified. So just before navigating to the quota available screen, the camera …
> fix: improve disabling of camera when screen not focused

- src/components/Login/utils.test.tsx
- src/components/Login/utils.ts
When phone number is 1 number, PhoneNumberUtil's parse throws an error that's unhandled
> fix: crash on single digit phone numbers

- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/Layout/AppHeader.tsx
- src/hooks/useLogout.tsx
- src/hooks/useValidateExpiry.tsx
- src/navigation/Content.tsx
- When app is freshly opened / became in focus
- If token is expired, logout immediately
- If token is about to expire (60mins), show banner
- When app has been kept open
- Whenever an NRIC is scanned, if about to expire (60mins), show banner 
- Once countdown reaches 0, logout immediately
| Countdown updates every minute | When less than a minute, changes every second | Automatic logout |
| --- | --- | --- |
|![Simulator Screen Shot - iPhone 11 Pro - 2020-04-20 at 16 24 41](https://user-images.githubusercontent.com/577802/79731111-641e7380-8324-11ea-9ddb-9b3bf264eca9.png)| ![Simulator Screen Shot - iPhone 11 Pro - 2020-04-20 at 16 29 22](https://user-images.githubusercontent.com/577802/79731106-61bc1980-8324-11ea-8ab2-28a1d3e4fb3b.png) | ![Simulator Screen Shot - iPhone 11 Pro - …
> feat: improve logout flow

- package-lock.json
Before:
```
found 1184 vulnerabilities (1156 low, 28 moderate) in 1837337 scanned packages
```
After:
```
found 628 low severity vulnerabilities in 1815658 scanned packages
288 vulnerabilities require semver-major dependency updates.
340 vulnerabilities require manual review. See the full report for details.
1 package update for 288 vulnerabilities involved breaking changes
(use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```
haha let's see how to reduce the number
> chore: fix vulnerabilities

- app.json
- src/components/Login/LoginContainer.tsx
- src/navigation/Content.tsx
Add support for links to open in SupplyAlly. Once published, a link will look like this:
```
supplyally://login?key=1234&endpoint=https://endpoint.com
```
To test, create a link with your key and endpoint. I've created a simple site to generate the link: https://kitkm.csb.app/
```
exp://exp.host/@musket/rationally/--/login?release-channel=48&key=KEY&endpoint=ENDPOINT
```
> feat: add support for deeplinks

- src/components/CustomerQuota/NoQuotaCard.tsx
- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
- src/types.ts
[Trello card](https://trello.com/c/wtJhbXEM/72-cdc-flow-voucher-redemption) | [Figma screen](https://www.figma.com/proto/vYCze8TIVyrbvuF7IZliRP/SupplyAlly?node-id=1343%3A1131&scaling=min-zoom) | [Corresponding backend PR](https://github.com/rationally-app/backend-api/pull/31/files)
This MR adds the following modifications to the Limit reached screen (confirmed with Eida):
* Copy change of "When limit was reached:" to "Items redeemed:" (or purchased for when the policy type is purchase)
* Bold each bullet header under "Items redeemed:"
* Remove bullet for each header under "Items redeemed:"
* Display identifiers under each bullet whenever they exist
* Space out each component on the screen
> feat: CDC limit reached flow

- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
- src/components/CustomerQuota/NoQuotaCard.tsx
- src/components/CustomerQuota/sharedStyles.tsx
[Trello card](https://trello.com/c/M8cUhOGi/106-fix-cross-emoji-in-limit-reached-screen-haha)
Looks like the fix was simple :D
For those interested, the issue was the font-family styling in AppText. It caused the red cross to be rendered as a black one instead.
```
fontFamily: "brand-regular"
```
> fix: red cross is now red and not black!!

- src/components/CustomerQuota/ItemsSelection/ItemStepper.tsx
- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
[Trello card](https://trello.com/c/FOWlOnLO/119-bug-checkout-can-happen-without-voucher-code-input)
This MR fixes the bug where sometimes users could checkout without inputting voucher codes. See Trello card for steps to reproduce. 
Issue was in mergeWithCart, where the identifier inputs were being overwritten.
Also did a bit of refactoring for unique code validation because I think we were unnecessarily validating N times when we can do it only 1 time.
Also made identifiers an optional parameter for updateCart, because it was difficult to debug where we were accidentally replacing identifier inputs with an empty array.
> fix: block checkout without voucher codes

- src/components/CustomerQuota/ItemsSelection/Item.tsx
- src/components/CustomerQuota/ItemsSelection/ItemNoQuota.tsx
[Trello card](https://trello.com/c/XEUVzOrt/100-hide-identifier-inputs-when-there-is-no-quota-left-for-a-product)
As the title suggests 😆  Also includes copy change of "Cannot purchase" > "Not eligible" when the item has already been redeemed
> feat: hide identifier inputs when no quota left

- src/components/CustomerQuota/CheckoutSuccess/RedeemedItem.tsx
- src/components/CustomerQuota/ItemsSelection/Item.tsx
- src/components/CustomerQuota/ItemsSelection/ItemCheckbox.tsx
- src/components/CustomerQuota/ItemsSelection/ItemIdentifier.tsx
- src/components/CustomerQuota/ItemsSelection/ItemIdentifiersCard.tsx
- src/components/CustomerQuota/ItemsSelection/ItemStepper.tsx
- src/components/Layout/InputWithLabel.tsx
- src/components/Layout/PhoneNumberInput.tsx
- src/components/Login/LoginMobileNumberCard.tsx
- src/components/Login/utils.test.tsx
- src/components/Login/utils.ts
- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
- src/services/envVersion/index.ts
- src/types.ts
- src/utils/validatePhoneNumbers.test.tsx
- src/utils/validatePhoneNumbers.tsx
[Trello card](https://trello.com/c/SvdJlgy9/87-ui-tt-token-quota-screen)
This PR adds
* Support for `visible` and `disabled` attributes for text/scan inputs for identifiers
* Support for `STRING`/`NUMBER`/`PHONE_NUMBER` for identifiers' text input type
* Validation of phone numbers before checking out
* Hide identifier input display on Checkout screen if less than 2 identifiers
* Minor copy changes
Assumptions:
* We will never have an identifier with `textInput.type === "PHONE_NUMBER"` and scan button is also visible/enabled
Will add support for different scanner types in a different PR so this doesn't become too large!
> feat: text input UI for identifiers v2

- src/components/CustomerDetails/InputNricSection.tsx
- src/utils/validateNric.tsx
[trello](https://trello.com/c/m2p4SHmr)
Currently "Enter Identification number" label wraps, quick fix to shorten label.
"Enter ID number" working for edge case (Nexus One)
> style: shorten id input label

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierPhoneNumberInput.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierScanButton.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierScanModal.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierTextInput.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/sharedStyles.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/validateBarcode.test.ts
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/validateBarcode.ts
- src/components/CustomerQuota/ItemsSelection/ItemIdentifier.tsx
- src/components/CustomerQuota/NoQuotaCard.tsx
- src/services/envVersion/index.ts
[Trello card](https://trello.com/c/SvdJlgy9/87-ui-tt-token-quota-screen)
This PR adds
* QR scanner option
* Validation of barcode and QR code scanned 
* Refactored the different types of identifier layouts into their own files
* (Extra) Fix for no quota screen to hide identifiers when they have no `value`. By right this case should never happen since we should have saved the identifiers to the db, but happened to find this, so just fix in case ah 😅 
Can test against [PR35](https://github.com/rationally-app/backend-api/pull/35)
> feat: scan input for identifiers v2 

- src/components/CustomerDetails/InputNricSection.tsx
- src/components/Layout/InputWithLabel.tsx
For NRIC input fields, so it doesn't show up in the user's keyboard suggestions
> feat: disable autocomplete and autocorrect

- src/navigation/Content.tsx
This issue only occurs on Android production builds. So was using `expo build:android` to actually get the apk and install it on my device.
Have added back the check to add `paddingTop`.
Will need to relook this again when upgrading to a later version of Expo. Looks like it could be a react-native issue where SafeAreaView does not properly care about the height of the status bar
> fix: content covered by status bar

- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
[Trello](https://trello.com/c/1p4FC27Q/192-ensure-app-doesnt-show-a-cart-with-negative-quantity)
Features:
- Check for negative quota received and display the limit reached screen if there are
- Sends a Sentry error ([without stacktrace](https://docs.sentry.io/error-reporting/capturing/?platform=javascript#capturing-errors--exceptions))
- Added tests for this case
> feat: no negative quota

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerQuota/AddUserModal.tsx
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/Layout/KeyboardAvoidingScrollView.tsx
- src/components/Login/LoginContainer.tsx
- src/components/MerchantPayout/MerchantPayoutScreen.tsx
- src/services/envVersion/index.ts
- src/services/quota/index.tsx
* Add use of KeyboardAvoidingView for quota screen
* KeyboardAvoidingView acts like a normal View but when the keyboard opens, it adds a bottom padding. By doing so, the view becomes shorter. When it wraps the scroll view, elements in the scroll view will still be able to be scrolled.
* Using `behavior="padding"` only on iOS makes it work properly. On android, specifying causes issues, leaving it undefined works fine
> feat: improved keyboard avoiding view

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_development_environment.yml
This PR includes:
- new ci/cd process with github actions
For setup:
- add `EXPO_CLI_USERNAME` and `EXPO_CLI_PASSWORD` into secrets
- create a `base-ref` tag for first release reference to compare to
- Read the documentation on the notion of how to operate ([https://www.notion.so/CI-CD-Documentation-Front-end-2c95eafd9f0948c09d11db3bc2ad4534#03d3256825ac4d82a75c5a1fb7f71d72](url))
> feat: added new ci/cd process

- app.json
This PR contains the increase in time out duration to 4seconds for automatic updates over-the-air (OTA): https://docs.expo.io/guides/configuring-ota-updates/#automatic-updates
> feat: updated cache timeout to 10s

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerDetails/InputIdSection.tsx
- src/components/CustomerQuota/AddUserModal.tsx
- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
- src/components/CustomerQuota/CustomerCard.tsx
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx
- src/components/CustomerQuota/NoQuotaCard.tsx
- src/components/CustomerQuota/NotEligibleCard.tsx
- src/hooks/useCart/useCart.test.tsx
- src/services/envVersion/envVersion.test.tsx
- src/services/envVersion/index.ts
- src/types.ts
- src/utils/validateIdentification.test.ts
- src/utils/validateIdentification.ts
- src/utils/validateInputWithRegex.test.tsx
- src/utils/validateInputWithRegex.ts
- storybook/stories/CustomerQuota/CheckoutSuccessCard.tsx
[notion](https://www.notion.so/Feature-Identification-scanning-Using-feature-flag-to-toggle-id-scanning-type-448e2acc9bb644dd9dbbaf38923d8960)
Proposed Solution:
Adding a new feature flag for scanner, toggling the type and validation
```
id: {
type: "STRING" || "NUMBER"
scannerType: "CODE_39" || "QR"
validation: "NRIC" || "REGEX"
validationRegex?: <regex for voucher and QR>
}
```
> feat: using new feature flag to toggle id scanning type

- src/utils/validateNric.test.tsx
- src/utils/validateNric.tsx
This PR contains a frontend fix for the NRIC regex. Previously was accepting NRIC with more than 9 digits.
> fix: bug fix for nric validation

- app.json
Right now the app.json version codes are not dynamic. Once https://github.com/rationally-app/mobile-application/pull/105 is done, it will be fully dynamic and will increment automatically.
In the meantime, this PR just bumps the version to 4.0.0, a breaking change because of the new sdk 38.
Also, from here on out, we'll sync up the `ios.buildNumber` and `android.versionCode`, and will start from 40.
> chore: release 4.0.0

- app.config.ts
- src/components/Layout/DrawerNavigation.tsx
We need to synchronize the buildNumber and `GITHUB_RUN_NUMBER` before building and releasing it to the app stores.
Also, added `appBuildVersion` into extra for easy consumption
> fix: sync build number

- src/components/Layout/DrawerNavigation.tsx
Align the hamburger menu icon and close button
| iPhone 8 | iPhone 11 Pro | Google Pixel 3a |
|-----|-----|-----|
|![Simulator Screen Shot - iPhone 8 - 2020-07-27 at 20 14 25](https://user-images.githubusercontent.com/577802/88540597-d26e8280-d045-11ea-94d3-9ee131f82d19.png)|![Simulator Screen Shot - iPhone 11 Pro - 2020-07-27 at 20 13 54](https://user-images.githubusercontent.com/577802/88540602-d5697300-d045-11ea-83ec-99adace1ccbb.png)|![image](https://user-images.githubusercontent.com/577802/88540632-e74b1600-d045-11ea-93c1-6ce88b36e252.png)|
> chore: realign nav drawer

- src/hooks/useCheckUpdates.tsx
Right now updates can only be checked every 60 minutes, there are situations where we will want to perform checks that are not constrained by this rule.
This PR also adds a return type so consumers can know the outcome of the check.
> feat: add ability to force check updates

- package-lock.json
- package.json
- src/context/campaignConfig.tsx
- src/navigation/index.tsx
- src/services/campaignConfig/campaignConfig.test.ts
- src/services/campaignConfig/campaignConfig.ts
- src/services/campaignConfig/index.ts
- src/types.ts
- src/utils/hash.ts
* Added a `campaignConfig` service that calls `${endpoint}/client-config` to retrieve the config.
* Added a `campaignConfig` context that allows consumers to retrieve the campaign config anywhere in the tree. This context exposes a `configHashes` that is updated every time a new configuration is saved and when it's loaded from async storage. This `configHashes` is used when calling the endpoint so that the endpoint does not need to return the same set of data if the client already has the most updated config
> feat: campaign config service

- src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.test.tsx
- src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.tsx
* This hook helps with the actual calling of the endpoint and saving to the context
* It provides stateful return values so that consumers can react to the changes. E.g. consumers can show a loading spinner when `fetchingState` is `FETCHING_CONFIG`
> feat: update campaign config hook

- src/config/index.tsx
- src/hooks/useCheckVersion/useCheckVersion.test.tsx
- src/hooks/useCheckVersion/useCheckVersion.ts
- tsconfig.json
This hook gets the version from `config` and compares it with the minimum version from the campaign config
Checks:
1. `config.APP_BINARY_VERSION` vs `features.minAppBinaryVersion`
2. `config.APP_BUILD_VERSION` vs `features.minAppBuildVersion`
**NOTE**
Location of the current app version is subject to change, depends on the navigation sidebar PR that configure the app version variables
> feat: check version hook

- app.json
Have added `["CAMERA", "VIBRATE"]` as these are the only two additional permissions found in the following link that we use.
https://docs.expo.io/versions/latest/config/app/#android > under permissions
>  To use ONLY the following minimum necessary permissions and none of the extras supported by Expo in a default managed app, set permissions to []. The minimum necessary permissions do not require a Privacy Policy when uploading to Google Play Store and are:
• receive data from Internet
• view network connections
• full network access
• change your audio settings
• draw over other apps
• prevent device from sleeping 
To use ALL permissions supported by Expo by default, do not specify the permissions key. 
To use the minimum necessary permissions ALONG with certain additional permissions, …
> chore: specify permissions

- src/hooks/useCart/useCart.tsx
Setting cart state before throwing error helps to fix this bug, thanks to @justin0108 ^^
> fix: double alert modal appears during error in checkout

- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/ErrorBoundaryContent.tsx
- storybook/stories/ErrorBoundary/ErrorBoundary.tsx
- storybook/stories/index.tsx
* Refactored error boundary content into a new component so it's easier to showcase in Storybook
* Use new styling for the error boundary to match the alert dialogs
> feat: update error boundary styles

- src/components/CustomerQuota/CustomerQuotaScreen.tsx
[Notion Reference](https://www.notion.so/Cancel-button-to-go-back-to-Scan-ID-main-page-instead-of-camera-scanning-feature-30e737b54d1147ef82a6cef2c32f2e79)
Applied a minor fix to alter the navigation behavior after clicking on "Cancel" in the Customer Quota Screen. 
- **Then**: User is brought back to the previous page, which is the scanner.
- **Now**: User is brought back to main page.
> fix: Changed navigate path for onCancel callback

- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx
- src/components/Login/utils.test.tsx
- src/components/Login/utils.ts
- src/context/alert.tsx
- src/hooks/useCart/useCart.test.tsx
- src/utils/validateIdentification.test.ts
- src/utils/validateIdentification.ts
- src/utils/validateIdentifierInputs.test.ts
- src/utils/validateIdentifierInputs.ts
- src/utils/validateInputWithRegex.test.tsx
- src/utils/validateInputWithRegex.ts
> fix: error dialog edge cases

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_development_environment.yml
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/CustomerQuota/ItemsSelection/ItemMaxUnitLabel.tsx
- src/components/CustomerQuota/NoQuota/AppealButton.tsx
- src/components/CustomerQuota/NoQuota/NoQuotaCard.test.ts
- src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
- src/components/CustomerQuota/NoQuota/ShowFullListToggle.tsx
- src/components/CustomerQuota/NoQuota/TransactionTitle.tsx
- src/components/CustomerQuota/NoQuota/TransactionsByCategory.tsx
- src/components/CustomerQuota/NoQuota/styles.ts
- src/components/CustomerQuota/NoQuotaCard.tsx
- src/components/CustomerQuota/sharedStyles.tsx
- src/context/alert.tsx
- src/hooks/usePastTransaction/usePastTransaction.test.tsx
- src/hooks/usePastTransaction/usePastTransaction.tsx
- src/services/quota/index.tsx
- src/services/quota/quota.test.tsx
- src/utils/getIdentifierInputDisplay.ts
> feat: show all past transactions on limit reached screen

- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
- src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
This is related to #170 and #171 .
Global limits messages should only display if there is a single item category for now, since we have not decided how to show global limits messages for policies with multiple categories.
> feat: Display global limits messages only if there is a single category

- .github/dependabot.yml
Set up dependabot to get weekly automatic version updates!
* [GitHub's blogpost](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)
* [Setup instructions](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates)
> chore: add dependabot.yml for npm deps

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_staging.yml
This PR contains a fix for the failing deploy branch preview for storybook possibly due to an update in expo-cli requiring the env variables to be restated in the workflow job.
> fix: input env var in deploy preview

- .github/workflows/test_e2e.yml
Since the E2E tests run on push to master, it may run concurrently with the staging deployment. This could result in our E2E tests not using the newly deployed staging Expo application, which is unintended
> feat: run e2e after staging is deployed

- src/utils/validateIdentifierInputs.test.ts
- src/utils/validateIdentifierInputs.ts
will we need a default regex validation? in the event phone number does not have a regex.
> fix: add additional validation for phone number identifier input using regex

- src/components/ErrorBoundary/ErrorBoundaryContent.tsx
The `ErrorBoundaryContent` was found to be empty, since the wrong translation keys were referenced.
This hotfix fixes that.
> hotfix: empty ErrorBoundaryContent 

- .github/workflows/test_e2e.yml
Currently, without `if: always()` specified at certain steps in the workflow, reports and notifications will only be triggered if tests pass (exit code = 0).  Report when tests fail (exit code > 0).
> fix: Trigger Slack Report when tests fail

- src/components/DailyStatistics/DailyStatisticsScreen.tsx
- src/components/DailyStatistics/TitleStatistic.tsx
- src/components/DailyStatistics/TransactionHistoryCard.tsx
- src/hooks/useDailyStatistics/useDailyStatistics.test.tsx
- src/hooks/useDailyStatistics/useDailyStatistics.tsx
- src/hooks/useDailyStatistics/utils.test.ts
- src/hooks/useDailyStatistics/utils.ts
[notion](https://www.notion.so/Disabled-chevrons-for-future-date-in-redemption-statistics-and-sorting-will-be-by-sort-property-b3226495c3b34d4fa7eea588c5d6fc12)
Completing certain UI changes that were not mentioned/confirmed in previous story!
> feat: redemption stats ui changes

- .github/pull_request_template.md
This PR adds a template for pull requests. After this is merged, [all new pull requests will automatically have the template.](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#pull-request-templates)
> docs: added PR template

- package-lock.json
- src/hooks/useCart/useCart.tsx
This PR removes an empty `if` block which honestly I am not sure why/how it got in :-( But here are some links:
* [Original PR which used this `if` block](https://github.com/rationally-app/mobile-application/pull/49/files#diff-bd918fb9c4a235da78054870ecaf899a7c46d43ab54320821be7c2f0d4b73561R206)
* [Second PR which removed the contents of the `if` block](https://github.com/rationally-app/mobile-application/pull/86/files#diff-bd918fb9c4a235da78054870ecaf899a7c46d43ab54320821be7c2f0d4b73561R247)
I am quite very sure the `if` block is not needed tho, and everything seems to be working fine as well.
> chore: remove unused if block

- src/components/Layout/PhoneNumberInput.tsx
- src/utils/phoneNumberFormatter.ts
[Notion link](https://www.notion.so/Spacing-in-Contact-number-62a744454055462ca8a94ba2857bd9bc) 
This PR adds: 
- Fix for contact number input where we were incorrect sending an extraneous digit (e.g. `+65912345670`, if the extraneous digit is 0) to the component.
> fix: Check new phone number before forwarding to component

- src/utils/phoneNumberFormatter.test.ts
- src/utils/phoneNumberFormatter.ts
[Notion link](https://www.notion.so/Spacing-in-Contact-number-62a744454055462ca8a94ba2857bd9bc) 
- A change from using `PhoneNumberFormat.NATIONAL` to `PhoneNumberFormat.INTERNATIONAL` as the former was padding some foreign numbers with 0 as per national standards.
Using `PhoneNumberFormat.NATIONAL` for formatting resulted in some region phone numbers being padded at the start with 0 (e.g. `+44 008566434545` being padded with two 0s at the start) since by national standards, the numbers `+44 008566434545` and `+44 8566434545` are equivalent.
By switching to `PhoneNumberFormat.INTERNATIONAL`, we preserve the original phone number since no padding of 0s will be performed. However, we will have to manipulate the international phone number in order to remove the country code …
> fix: Foreign numbers in PhoneNumberInput not formatting properly

- src/components/CustomerQuota/CustomerQuotaScreen.tsx
[Notion link](https://www.notion.so/Error-in-Contact-Number-incorrectly-goes-back-to-Collect-Customer-Details-screen-999dd38b6f9e410fa20e9e717024ce69) 
- Fix to default case when handling errors in `CustomerQuotaScreen` to stay in current screen instead of going back to the previous screen
> fix: stay in current screen if error occurs in CustomerQuotaScreen

- .github/workflows/deploy_prod.yml
Currently trying to rerun a failed `create release` github action fails as the changelog action errors out. By setting the explicit `head-ref` and `base-ref`, we let the action know the exact changelog to generate, and update the old one if need be. This allows us to rerun the failed actions multiple times.
> chore: CI changelog improvements

- .github/workflows/deploy_prod.yml
Tags were not being fetched properly in `create_release`, so `git tag` was returning only the latest tag, causing the changelog generation to fail.
> chore: ensure tags are fetched properly

- src/components/Layout/DrawerNavigation.tsx
Related to: [Bug: IOS & Android Scale Right Tab](https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=9c15e648671e482ba2b53071cc0c2412)
- To scale at max font and max display size for IOS & Android.
**For IOS**
Max Font & Max Display Size:
Default:
**Android**
Max Font & Max Display Size:
Note: Scaled Help & Support to appear within view so that users will know and can scroll down.
Alternative:
Default:
**Dynamic Scaling**
ScrollView is parent view, the parent view wouldn't allow more height so when specify with flexGrow, the container can grow up to flex 1. 
So when the View set to flex 1 , then it can take the space.
-using const { height: HEIGHT } = Dimensions.get("window"); 
- with minHeight: HEIGHT * 0.6  
- This will always be …
> fix: added scroll view for nav drawer

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_development_environment.yml
- .github/workflows/test_e2e.yml
This PR specifies the ubuntu version to 18.04, instead of using ubuntu-latest.
This is due to actions/virtual-environments#1816
There is an update that would point ubuntu-latest to ubuntu-20.x, as we're currently using 18, I thought of just fixing this at 18 first.
We can revisit this again to update this to ubuntu-latest once things have stabilised after migration haha
> chore: freeze ubuntu image to 18.04 instead of latest

- src/hooks/useQuota/useQuota.test.tsx
- src/services/quota/index.tsx
This PR adds an additional check for the `NotEligibleError`.
Currently, new distributions will start using the backend whitelisting, instead of mystique. However the backend whitelist is currently throwing a slightly different error compared to the standalone mystique.
We will cater for both error messages for now, as the backend whitelist error message is currently handled on other distributions.
~I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components~
~I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)~
~I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799 …
> feat: handle new error message from backend whitelist

- src/components/CampaignInitialisation/CampaignInitialisationScreen.tsx
- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/context/identification.tsx
[Notion link](https://www.notion.so/When-I-hv-multiple-distributions-campaigns-logged-in-switching-from-one-to-another-causes-validatio-7f7cf92215b6496baec0e1c56a818407) 
- Fix that ensures the correct ID validation rules are loaded when switching between different campaigns.
The condition used to determine if the existing validation rules should be used was always returning `true` since it was matching `undefined === undefined`. This resulted in the bug where the first loaded campaign's validation rules would always be used, instead of using each campaign's validation rules when changing between campaigns.
> fix: Multiple Campaign ID Validation 

- src/components/CustomerDetails/ManualPassportInput.tsx
[Notion link](https://www.notion.so/TT-Token-passport-holder-Submit-button-label-and-Repositioning-of-Go-to-Statistics-button-Frontend--9bc9bccea65e4f328a7238cc6da7a166)
This PR updates the passport input tab to make use of translations so that it follows the normal nric input tab
> chore: "check" instead of "submit" for passport input

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
[Notion link](https://www.notion.so/TT-Token-passport-holder-Submit-button-label-and-Repositioning-of-Go-to-Statistics-button-Frontend--9bc9bccea65e4f328a7238cc6da7a166)
This PR moves the statistics button to be outside the card. Have also reduced the top margin.
> chore: move statistics button

- src/utils/phoneNumberFormatter.test.ts
- src/utils/phoneNumberFormatter.ts
This PR removes the formatting of phone numbers which go above the `exampleNumber`'s length.
> fix: remove phone number length restriction

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/context/alert.tsx
- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/To-show-alert-in-FE-TT-Token-issuance-6c4a83cabae740e5b8a4a8173167a97c) 
- to show the alert modal, when the tt-token validation failed
> feat: to show alert modal for validation of tt-token issuance

- .github/workflows/test_e2e.yml
[Notion link] https://www.notion.so/Remove-pCloudy-API-Key-from-mobile-e2e-repo-and-refer-to-E2E_PCLOUDY_API_KEY-secret-in-GitHub-c8fdf1bddc304c1da031c2c1cca26605
1. Now the pCloudy API-keys and server details will be fetched from github secrets
> use pcloudy Api Keys details from github secrets

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/Login/LoginOTPCard.tsx
[Notion link](https://www.notion.so/Missing-translation-in-error-message-when-user-enters-wrong-OTP-too-many-times-9463bbf7d3fc4e51b4ec5b240a6af033)
This PR fixes the error message for when a user retries submitting OTP too many times.
> fix: error message when user retries submitting OTP too many times

- .github/workflows/test_e2e.yml
GitHub actions now support manually triggered workflows. Have enabled this for e2e tests so that we can run it on the fly.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
Example:
> chore: allow manual e2e workflow runs

- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
- src/hooks/useQuota/useQuota.test.tsx
- src/types.ts
The quota endpoint returns an identifierInputs field that represents the values of the latest transaction. In `mergeWithCart` we were treating those values as the template for the identifierInputs. This meant that we were incorrectly using the latest transaction values as the initialised value for the cart.
This works for most cases since the identifier inputs returned from the last transaction will match the identifier inputs from the latest transaction. However, the assumption isn't always valid and this PR corrects this logic.
> fix: issue with mergeWithCart using the quotaResponse incorrectly

- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/Return-TT-Token-FrontEnd-Changes-69860c2451a94f89bba3c9fa34ac02f9) 
- new cartState: UNSUCCESSFUL. This cartState is for the `tt return flow`. It will be triggered when a user attempts to return the wrong token
> feat: implement UNSUCCESSFUL cartState condition

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
- src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
- src/components/Layout/Buttons/HelpButton.tsx
[Notion link](https://www.notion.so/Translation-c13n-and-i18n-standardisation-a249a80094c946d490ba479f6ed58fae) 
- refactors punctuations into translations file ( `en.ts` and `zh.ts` )
- updated `c13n/en` parameter store for `pr471`
Currently, c13nt method is only used in several components:
- NotEligibleCard
- notEligibleDescription
- CheckoutSuccessCard
- checkoutSuccessTitle
- checkoutSuccessDescription
- CheckoutUnsuccessfulCard
- checkoutUnsuccessfulTitle
- checkoutUnsuccessfulDescription
- NoQuotaCard
- chechkoutSuccessPreviousItems
> feat: refactoring punctuations to translation texts.

- src/hooks/usePastTransaction/usePastTransaction.test.tsx
- src/hooks/usePastTransaction/usePastTransaction.tsx
- src/services/quota/index.tsx
- src/services/quota/quota.test.tsx
[Notion link](https://www.notion.so/After-return-TT-Token-non-chargeable-transaction-history-are-removed-from-view-but-retains-Chargea-6ea0b27743e7433c96432fb373b3d3cb) 
- added hooks for updating and resetting categories
- altered API call to transaction history endpoint
> feat: add filtering by categories for past transactions

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierScanButton.tsx
- src/components/CustomerQuota/ItemsSelection/ItemIdentifier.tsx
- src/components/Layout/Buttons/DarkButton.tsx
- src/components/Layout/PhoneNumberInput.tsx
[Notion link](https://www.notion.so/Phone-number-scanning-68b12284ee2e40f9bf4fdc37e00b07ae)
This PR removes the text from the scan buttons when inputting identifier inputs. Purpose is to ensure there's sufficient space for phone number fields
> chore: identifier scan button should only show an icon

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierPhoneNumberInput.tsx
- src/components/CustomerQuota/ItemsSelection/ItemIdentifier.tsx
- src/components/Layout/PhoneNumberInput.tsx
- src/utils/validatePhoneNumbers.test.tsx
- src/utils/validatePhoneNumbers.tsx
[Notion link](https://www.notion.so/Phone-number-scanning-68b12284ee2e40f9bf4fdc37e00b07ae) 
This PR adds ability to scan a phone number.
* Fixes alignment issue when the scan button is enabled
* Add logic to handle the scanning of the following types of numbers:
* `91234567`: no country code, will default to SG
* `+65 81234567`, `+12024561414`: has country code, will update the country code input to match what was scanned
* `65 91234567`, `6581234567`, `12024561414`: has country code without `+` sign, will default to SG.
> feat: phone number scanning

- src/components/CustomerQuota/ItemsSelection/AddonsItems.tsx
- src/hooks/usePastTransaction/usePastTransaction.test.tsx
- src/hooks/usePastTransaction/usePastTransaction.tsx
- src/services/quota/index.tsx
- src/services/quota/quota.test.tsx
This PR adds `getAllTransactions` flag to `usePastTransactions` in accordance to the updated BE `getGroupTransactions` function. Also, updates the affected unit tests
> Fix: use past transactions missing flag

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierPhoneNumberInput.tsx
Ensure that value from parent is handled before other useEffects by using useLayoutEffect
> chore: useLayoutEffect to handle parent phone number updates

- src/hooks/usePastTransaction/usePastTransaction.tsx
This ensures that the errors are logged in a single category on Sentry. Now they are scattered across many different categories.
> chore(past-tx): move the logging of IDs to a breadcrumb

- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/When-selecting-2-NRICs-in-Engineering-Good-campaign-the-checkbox-does-not-turn-into-a-stepper-826f45042f4e4b3b815bb8341f22e3ea) 
- Cart quota now updates whenever the quota response changes
> fix: cart quota not updating

- src/components/Layout/Stepper.tsx
- src/hooks/useIsMounted.tsx
- src/hooks/usePastTransaction/usePastTransaction.tsx
#~NOTE: Rebase commits once the target PR is merged~
There's been a yellow box warning whenever past transactions is called on the checkout success screen.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function,
in CheckoutSuccessCard (at CustomerQuotaScreen.tsx:282)
in RCTView (at CustomerQuotaScreen.tsx:270)
in RCTView (at ScrollView.js:1063)
in RCTScrollView (at ScrollView.js:1196)
in ScrollView (at KeyboardAvoidingScrollView.tsx:24)
in RCTView (at KeyboardAvoidingView.js:218)
in KeyboardAvoidingView (at KeyboardAvoidingScrollView.tsx:20)
in KeyboardAvoidingScrollView (at CustomerQuotaScreen.tsx:267)
``` …
> chore(past-tx): handle unmounted error when fetching

- src/hooks/useQuota/useQuota.test.tsx
- src/hooks/useQuota/useQuota.tsx
- An additional check in `hasNoQuota` to check for empty whether `remainingQuota` is empty before running `every` on it, since it returns true if the array is empty.
Note that we want `hasNoQuota` to return true when `remainingQuota` is either:
- empty, or
- all of the items have zero quantities
> fix: add checks for empty array in hasNoQuota

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CampaignInitialisation/CampaignInitialisationScreen.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/ErrorBoundaryContent.tsx
- src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.test.tsx
- src/services/campaignConfig/campaignConfig.ts
- src/services/helpers.ts
- storybook/stories/ErrorBoundary/ErrorBoundary.tsx
[Notion link](https://www.notion.so/FE-App-opening-error-systemErrorConnectivityIssues-06a63d77c8c346a19f49755b22a1dc43) 
- Added new error type `NetworkError`, which is thrown when `fetch` fails in `fetchWithValidator`.
- Added error handling for `NetworkError` when fetching campaign configuration.
Previously, if the device is offline, an error dialog will be shown to the user. Upon dismissal of the error dialog, the user will be met with a perpetual loading screen. 
This fix changes this behavior by allowing the `ErrorBoundary` to catch the errors above (i.e. network errors), and providing the user with a screen where they are able to restart the application if needed, or report the error.
> fix: handle network errors when fetching campaign config

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerQuota/ItemsSelection/Item.tsx
- src/context/alert.tsx
- src/types.ts
- src/utils/validateIdentifierInputs.test.ts
- src/utils/validateIdentifierInputs.ts
[Notion link](https://www.notion.so/Update-policy-to-charge-lost-TT-Tokens-if-it-s-lost-for-a-2nd-time-Enter-Payment-receipt-number-28a3cb5dfdbc4e9e95a21a1b1490db0a) 
This PR adds the payment receipt field in IdentifierInputs if it's chargeable. Relies on backend api PR532. WIP!
Will be using filter instead of splice, mainly because `splice` makes changes to the `policies` 
```
Array.splice - will change the Array itself. (use: myArray.splice)
Array.filter - will return the filtered Array. (use: myFilteredArray = Array.filter)
```
> feat: only show payment receipt field upon chargeable

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierScanModal.tsx
- src/types.ts
Currently type BARCODE defaults to code_39. This PR introduces 2 new types code_39 and code_128 to make the barcode type more explicit.
[Notion link](https://www.notion.so/Update-policy-to-charge-lost-TT-Tokens-if-it-s-lost-for-a-2nd-time-Enter-Payment-receipt-number-28a3cb5dfdbc4e9e95a21a1b1490db0a)
> feat: support barcode type 39 and 128

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerAppeal/ReasonSelection/ReasonItem.tsx
- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerDetails/ManualPassportInput.tsx
[Notion link](https://www.notion.so/Chinese-translation-for-labels-Go-to-Statistics-Chargeable-Nationality-and-Passport-number-8078778d817e44f0bfa1029be3e50d6a) 
- new i18nt
- `collectCustomerDetailsScreen.goToStatistics`
- `collectCustomerDetailsScreen.nationalityInputLabel`
- `collectCustomerDetailsScreen.passportInputLabel`
- new c13nt for campaign specific description alert.
- *chargeable
> chore: add chinese translations for labels

- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierPhoneNumberInput.tsx
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierTextInput.tsx
This PR uses label in accessibilityLabel for IdentifierTextInput and IdentifierPhoneNumberInput. This allows us to differentiate each identifierInput, as each of them will have a unique accessibilityLabel. This would help the e2e tests and reduce reliance on indexes and order of the identifiers.
Current behaviour:
- all text input type that is `PHONE_NUMBER` will have an accessibility label of `item-field-phone-number`
- all other text input type will have an accessibility label of `item-field-text`
New behaviour:
- for text input type with `PHONE_NUMBER`, if label is present, we will now format as `<label>-phone-number`. E.g. `Main Contact` will result in `main-contact-phone-number`
- for all other text input, we will now format as `<label>-text`. E.g. `Designation` will result in …
> feat: create unique accessibility labels for each identifier

- src/hooks/useCart/useCart.tsx
- src/hooks/usePastTransaction/usePastTransaction.tsx
- src/hooks/useQuota/useQuota.tsx
- src/services/quota/index.tsx
- src/services/quota/quota.test.tsx
- src/types.ts
[Notion link](https://www.notion.so/FE-path-toggling-for-mobile-application-502f314239cc4effb72d7134f4bd0975) 
This PR adds a new feature flag `apiVersion` that is used to perform toggling between different version of endpoints on our app.
> feat: toggle endpoints versions using feature flag

- package-lock.json
- package.json
The Snyk PR has issues with our CI. This PR also updates `react-native-webview` to the very latest.
Have tested the HelpModal, works fine!
| | |
|--|--|
|![image](https://user-images.githubusercontent.com/577802/116640704-c1b8b780-a99d-11eb-853a-2f9977122c26.png)|![image](https://user-images.githubusercontent.com/577802/116640711-c4b3a800-a99d-11eb-8abf-3875a23c71b6.png)|
> chore(deps): update react native webview

- package-lock.json
This PR bumps the version of y18n from 4.0.0 to 4.0.3. For more info: https://npmjs.com/advisories/1654
After bump:
```
$ npm ls y18n
├─┬ jest@26.6.3
│ ├─┬ @jest/core@26.6.3
│ │ └─┬ jest-runtime@26.6.3
│ │   └─┬ yargs@15.4.1
│ │     └── y18n@4.0.3  deduped
│ └─┬ jest-cli@26.6.3
│   └─┬ yargs@15.4.1
│     └── y18n@4.0.3 
├─┬ jest-expo@40.0.2
│ └─┬ jest@25.5.4
│   └─┬ jest-cli@25.5.4
│     └─┬ yargs@15.4.1
│       └── y18n@4.0.3  deduped
├─┬ react-native@0.62.2
│ ├─┬ @react-native-community/cli@4.10.1
│ │ └─┬ metro@0.58.0
│ │   ├─┬ metro-inspector-proxy@0.58.0
│ │   │ └─┬ yargs@14.2.3
│ │   │   └── y18n@4.0.3  deduped
│ │   └─┬ yargs@14.2.3
│ │     └── y18n@4.0.3  deduped
│ └─┬ @react-native-community/cli-platform-android@4.7.0
│   └─┬ logkitty@0.6.1
│     └─┬ yargs@12.0.5
│       └── …
```
> chore(deps): bump y18n from 4.0.0 to 4.0.3

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- reformat passport manual input
> refactor: format the string input before passing to onCheck for manual

- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/Invalid-Error-Dialog-Message-during-TT-Token-Validation-718769b3f61f4a689a678d9ebf67e2a4) 
- handles case when old appeal token does not have any `identifierInputs`
> fix: handle case during token validation when token has no `identifierInputs`

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/utils/passportScanning.test.ts
- src/utils/passportScanning.ts
- add function to extract passport id from event
- add tests for different JSON strings
- add tests for different strings
> feat: extract passport id from event

- src/utils/passportScanning.test.ts
- src/utils/passportScanning.ts
[Notion link](https://www.notion.so/Passport-Scanner-Edge-Cases-null-8057773fada0480f90661edfa53fa6ac) 
- handling of `null` type case when scanning passport
> feat(pp): handle `null` type case

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/CustomerQuota/NotEligibleCard.tsx
- src/context/alert.tsx
- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/FE-Error-handling-of-whitelisted-beneficiaries-that-do-not-have-any-disbursements-45e33974693e43e6aff9945fa10129b7) 
This PR handles the possibility where quota returned is empty for `v2/quota` endpoint, i.e. :
```
{
"remainingQuota": Array [],
"globalQuota": Array [],
"localQuota": Array [],
}
```
which could happen when a beneficiary is whitelisted, but not disbursed any credits.
> feat: handle missing disbursements resulting in empty quota

- src/types.ts
- src/utils/validateIdentifierInputs.test.ts
- src/utils/validateIdentifierInputs.ts
- remove mandatory `value` for `PAYMENT_RECEIPT`
- update `PolicyIdentifier` type
I think 
``` typescript
if (textInputType !== "PAYMENT_RECEIPT" && !value) {
throw new Error(ERROR_MESSAGE.MISSING_IDENTIFIER_INPUT);
}
```
can be removed instead. Empty `value` will still be checked in the `regex` matching as well as BE validation
> feat: PAYMENT_RECEIPT to have optional value.

- src/common/i18n/translations/en.ts
- src/components/CustomerQuota/ItemsSelection/ItemMaxUnitLabel.tsx
[Notion link](https://www.notion.so/Remove-extra-after-a5e6eadca9154af1982892c508137266) 
This PR adds removes the extra period after 最多 (chinese for max) in items selection page.
> fix: remove extra period after 最多

- app.json
[Notion link](https://www.notion.so/Toggle-backup-to-be-false-in-android-manifest-xml-L002-6f48c5b3cf0f4de2be77d9212ba8dfcf)
> chore: allowBackup should be false

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/DailyStatistics/StatisticsHeader.tsx
- src/components/DailyStatistics/TitleStatistic.tsx
- src/components/DailyStatistics/TransactionHistoryCard.tsx
- src/hooks/useDailyStatistics/useDailyStatistics.test.tsx
- src/hooks/useDailyStatistics/useDailyStatistics.tsx
- src/hooks/useDailyStatistics/utils.test.ts
- src/hooks/useDailyStatistics/utils.ts
[Notion link](https://www.notion.so/Chinese-translation-for-app-Redemption-Statistics-1cbd66b827b74892a1d072109b438a47) 
This PR adds Chinese translation to the remaining texts that are still in English on the stats page.
> feat: chinese translation stats page

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierSelectionInput.tsx
- IdentifierSelectionInput placeholder to use c13nt and to have default i18nt
> feat: identifierSelectionInput placeholder to use c13nt

- src/components/CustomerQuota/ItemsSelection/AddonsItems.tsx
- src/components/CustomerQuota/ItemsSelection/ItemCheckbox.tsx
- revert categoryFilter in AddonsItems and ItemCheckbox to only show its own category
> chore: addonToggle to only show its own category

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/zh.ts
[Notion link](https://www.notion.so/First-lost-token-should-not-be-in-waived-charges-transaction-history-and-changed-labels-to-Related-h-12403df0ec604534ba89df697f482dd6) 
- update `Chargeable` translation
- update `waive charges` translation
> chore: update addonToggleComponents translations

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_development_environment.yml
This PR limits the number of concurrent job runs for the following Github workflows:
- deploy_branch_preview
- deploy_prod
- deploy_staging
- test_development_environment
I've not added concurrent limits for the test_e2e, as I think that needs more research as the triggers include workflow dispatches that `github.ref` doesnt cover. `github.ref` only coveres branch or tag ref.
> build: limit concurrency runs for all github workflows

- src/components/CustomerQuota/ItemsSelection/AddonsItems.tsx
- src/components/CustomerQuota/ItemsSelection/ItemCheckbox.tsx
- src/components/CustomerQuota/ItemsSelection/ItemContent.tsx
- src/components/CustomerQuota/ItemsSelection/ShowAddonsToggle.tsx
- src/components/CustomerQuota/TransactionsGroup.tsx
- src/components/Layout/Checkbox.tsx
[Notion link](https://www.notion.so/Related-history-accordion-should-not-appear-if-there-isn-t-any-past-transaction-185aebbb017a4bfabfa4e421cc538e8c) 
- addons Toggle now shows only when transactionList exists
- refactor ItemContent to not have ShowAddonsToggle
- separate ShowAddonsToggle to its own component under Checkbox
(if this component is to be used in more identifier inputs, will try to put in more generic location)
> refactor: addons toggle to only show when transactionList exists

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/zh.ts
The "Expired" error message is shared between to error instances, `AuthExpiredError`, `AuthNotFoundError`, `SessionError`. Below are the methods to evoke the dialog messages through different error instances.
**AuthExpiredError (`AUTH_FAILURE_EXPIRED_TOKEN`)**
- Generate a campaign with not yet valid validity period ⇒ try to login
- Generate a campaign with already expired validity period ⇒ try to login
**AuthNotFoundError (`AUTH_NOT_FOUND`/`AUTH_ROLE_UNAUTHORIZED`)**
- Generate a campaign with invalid `uuid` ⇒ try to login
- Generate a campaign ⇒ modify its user `role` in dynamodb to not be `OPERATOR` ⇒ call any `authenticatedRequestHandler()` API
**SessionError**
- Login to a campaign ⇒ change its sessionToken ⇒ Login to a campaign
more details in the [Notion …
> feat: more generic error message for validity period errors

- package-lock.json
- package.json
- src/utils/validatePhoneNumbers.test.tsx
[Notion](https://www.notion.so/Phone-number-throwing-invalid-error-although-it-s-valid-5697015c1edd4891bc56a7c0aba53e1e)
A user reported that their number starting with 8023 doesn't pass validations.
Upon further investigation, updating to the latest `google-libphonenumber` allows it to work.
Before:
```
● mobileNumberValidator › should return true for valid numbers
expect(received).toBe(expected) // Object.is equality
Expected: true
Received: false
111 |     expect(mobileNumberValidator("+65", "98261749")).toBe(true);
112 |     expect(mobileNumberValidator("+65", "98219374")).toBe(true);
> 113 |     expect(mobileNumberValidator("+65", "80230000")).toBe(true);
|                                                      ^
114 |   });
115 | });
116 | 
at Object.<anonymous> …
```
> chore(deps): update google-libphonenumber

- src/components/IdScanner/IdScanner.tsx
[Notion link](https://www.notion.so/Cannot-scan-login-QR-code-after-upgrading-Expo-to-SDK-42-d23580a167784ff595c43bbe5541db37) 
- fix bounding box logic for physical android devices. InterestArea now takes the correct `width` and `height` addition
(tested with physical android, emulator android, and physical iPhone)
> fix: interestArea now takes the correct width and height

- src/components/DailyStatistics/TransactionHistoryCard.tsx
[Notion link](https://www.notion.so/Statistics-page-quantity-alignment-issue-7049a3eb107a4989bac484c6099bac21)
This PR adds the fix to the overflow issue on the statistics page when 3 digits or above quantity is issued to an item on phone screens with display zoom set above a certain limit (max zoom). 
2 environments were used to test this out:
1: Mocking `transactionHistory` data to have `Dead Battery (1 to 1 exchange)` set to 1500 quantity on `npm run storybook` on the statistics screen. 
2: Using [PR-791](https://github.com/rationally-app/backend-api/pull/791) backend environment on Expo with editted policies from parameter store to increase limit redemption to 9999 when raising appeal.
> fix: overflow on statistics page

- .github/workflows/deploy_branch_preview.yml
This PR adds a lint check to ensure that PR title will follow conventional commits specs
Sample error thrown if PR title is wrong
```
Error: No release type found in pull request title "wrong/ lint PR titles and minor github workflow updates". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/
Available types:
- feat: A new feature
- fix: A bug fix
- docs: Documentation only changes
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- refactor: A code change that neither fixes a bug nor adds a feature
- perf: A code change that improves performance
- test: Adding missing tests or correcting existing tests
- build: Changes that affect the build …
```
> build: ensure PR title follows conventional commits specs

- src/components/CustomerDetails/InputPassportSection.test.tsx
- src/components/CustomerDetails/InputPassportSection.tsx
[Notion link](https://www.notion.so/Trim-extra-leading-or-trailing-spaces-from-user-input-738d72c9467740d9b5e77b3b4828cf28) 
This PR adds the fix for passport numbers not being validated found during testing of trailing and leading whitespace for non NRIC signup values.
> fix: trim passport num logic

- .github/dependabot.yml
- .github/workflows/test_development_environment.yml
This PR adds
- dependabot will check for github-actions updates every month
- test_development_environment will test for node 12,13,14 instead of 10,12,13
> build: GitHub workflow updates

- .github/workflows/deploy_prod.yml
Expo changed their domain TLD to .dev
Found out by looking at the difference between the last 2 deploys:
(success)
`[03:07:30] Successfully built standalone app: https://expo.io/artifacts/8aa9a7b7-2197-49cc-9350-0c963205ebd6`
vs
(failure)
`[03:08:51] Successfully built standalone app: https://expo.dev/artifacts/9eb33980-0605-4086-a82e-743f849e6876`
Turns out expo changed domain: https://github.com/expo/expo-cli/pull/3771
> build: fix deploy prod url

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/test_e2e.yml
- README.md
[Notion link](https://www.notion.so/sally-wallet/Deprecate-musket-dev-e0334798edd94330b58b176b76cd82c7) 
This PR replaces usage of `musket-dev` bot user with `supplyally-bot` in our build workflows.
Also replaced use of default `GITHUB_TOKEN` to be consistent.
> build: replace musket-dev with supplyally-bot

- src/components/CustomerQuota/ItemsSelection/Item.tsx
- src/components/CustomerQuota/utils.test.ts
- src/components/CustomerQuota/utils.ts
- src/types.ts
- src/utils/validatePassport.ts
[Notion link](https://www.notion.so/sally-wallet/Part-1-of-2-Update-policy-and-Sally-screens-for-TT-Token-Passport-collection-collect-money-upon-1s-30f8b583dbf64a7bb8dd5acc90f877b0) 
- `isPodChargeable` now checks `tt-token`'s PAYMENT_RECEIPT field
> feat: add payment_receipt to `tt-token` category

- src/components/CustomerAppeal/ReasonSelection/ReasonSelectionCard.tsx
- src/components/CustomerQuota/CustomerCard.tsx
The CustomerCard ID background colour was defined in the styles with a default colour previously, which should be superseded by each type of CustomerCard (successful/unsuccessful). This was missed out in the theme.
> fix: customer identification number background colour

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerDetails/InputIdSection.tsx
- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
- src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
- src/components/CustomerQuota/NoQuota/TransactionTitle.tsx
- use of c13n for previously hardcoded app text
- toggle these text based on SSM params `en` and `zh` if they exist
> refactor: use c13n instead of hardcoded copy changes for GW theme

- src/components/CustomerAppeal/CustomerAppealScreen.tsx
- src/components/CustomerQuota/utils.test.ts
- src/components/CustomerQuota/utils.ts
[Notion link](https://www.notion.so/sally-wallet/Part-2-of-2-Update-policy-and-Sally-screens-for-TT-Token-Passport-collection-collect-money-upon-1s-ded1eb59d6f74dc6be172fd69fef73ea) 
- `PAYMENT_RECEIPT` field to all `PASSPORT` input
- remove `tt-token-lost-waive` appeal block from `PASSPORT` entry
> feat: tt token passport part 2

- src/components/CustomerAppeal/CustomerAppealScreen.tsx
- src/hooks/useCart/useCart.tsx
[Notion link](https://www.notion.so/sally-wallet/Part-2-of-2-Update-policy-and-Sally-screens-for-TT-Token-Passport-collection-collect-money-upon-1s-ded1eb59d6f74dc6be172fd69fef73ea) 
- require payment for passport user redeeming first lost token
> feat: add payment for passport first lost

- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerDetails/InputPassportSection.test.tsx
- src/components/CustomerDetails/InputPassportSection.tsx
- storybook/stories/CustomerDetails/InputsElements.tsx
[Notion link](https://www.notion.so/sally-wallet/De-sync-between-passport-number-field-and-what-is-submitted-4277f5c27bae45879369ad3ea99e813a)
This PR fix de-sync between passport number field and what is submitted.
> fix: De-sync between passport number field and what is submitted

- src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
Made a change to 2 of the translation keys indadvertedly 😢 
- Should be `CheckoutSuccessTitle` instead of `redeemed` 
- Should be `CheckoutSuccessDescription` instead of `redeemedItems`
- corrected keys for 2 elements 
- also made the change on SSM
> fix: key error for copy changes, translation

- src/hooks/useCart/useCart.tsx
- src/types.ts
- src/utils/paymentQRHelper.test.ts
- src/utils/paymentQRHelper.ts
- src/utils/paymentQrValidation.ts
[Notion link](https://www.notion.so/sally-wallet/Parse-Validate-and-Save-into-s3-Leverage-Sally-app-to-capture-payment-QR-for-merchant-ringfencing-a4f8b184c0114285b4fd2c4bf44f427d) 
- Utilities for parsing and storing `PAYMENT_QR` and its properties
- Parse`PAYMENT_QR` identifiers and update existing identifiers if they `isOptional` is `true` and their `label`s match parsed payment QR
> feat: parse and store `PAYMENT_QR`

- package-lock.json
- package.json
- src/utils/paymentQRHelper.ts
- src/utils/paymentQrValidation.ts
[Notion link](https://www.notion.so/sally-wallet/Parse-Validate-and-Save-into-s3-Leverage-Sally-app-to-capture-payment-QR-for-merchant-ringfencing-a4f8b184c0114285b4fd2c4bf44f427d#25d7316c1b124cb8b35b50c69691e7cd) 
- Updates `@rationally-app/payment-qr-parser` from `1.7.0` to `2.1.4`
- Adds `checkExpiry` toggle to `parsePaymentQR` to prevent checking of expiry dates in `@rationally-app/payment-qr-parser`, since it does not play nice with Android
> fix: add expiry check toggle to `parsePaymentQR`

- package.json
Add nuke-cache npm script to ensure local builds use the latest version of libraries
> chore: add nuke-cache npm script

- .github/workflows/deploy_branch_preview.yml
changing the lint action to use default GITHUB_TOKEN as it is sufficient for it, no need to provide it with our bot token
> build: change lint step to use GITHUB_TOKEN

- .github/workflows/deploy_prod.yml
- Adds `NODE_OPTIONS: --max_old_space_size=7168` to `expo build` steps for Android and IOS when deploying to production
When the "Build Android Release" and "Build IOS Release" steps are run, we get the following error (see [logs](https://github.com/rationally-app/mobile-application/runs/4946935531?check_suite_focus=true)):
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
> build(deploy_prod): add `expo build` `max_old_space_size=7168`

- src/context/alert.tsx
[Notion link](https://www.notion.so/sally-wallet/Remove-misleading-Sentry-logs-A-missing-translation-of-scope-errorMessages-X-secondaryActionText--c8debc4e7b59415e8a6ba0e198db42a3)
This PR remove misleading sentry logs that display alert that has no secondary action.
> fix: remove misleading sentry logs

- src/components/Login/LoginOTPCard.test.tsx
- src/services/auth/index.tsx
[Notion link](https://www.notion.so/sally-wallet/Fix-error-message-when-OTP-is-entered-incompletely-in-SupplyAlly-220f88075377460fb5335d4f6962603a) 
This PR fix error message when otp is entered incompletely.
> fix: error message when otp is entered incompletely

- src/common/i18n/translations/en.ts
- src/common/i18n/translations/type.ts
- src/common/i18n/translations/zh.ts
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/context/alert.tsx
- src/hooks/govwallet/useGovWalletBalance/useGovWalletBalance.test.tsx
- src/hooks/govwallet/useGovWalletBalance/useGovWalletBalance.tsx
- src/services/govwallet/balance/balance.test.tsx
- src/services/govwallet/balance/index.tsx
- src/services/helpers.ts
[Notion link](https://www.notion.so/sally-wallet/Error-handling-when-Sally-calls-GovWallet-v2-customer-account-get-for-MINDEF-SAFRA-campaign-f442fe104e0b49bd931998d034b5755e?v=532cc4d27b0641d69c5f34e3f6f0ab78) 
- Only show GovWallet balance error dialogs if there are no quota related errors.
- Add new error class `ErrorWithCodes`, which includes `statusCode` and `errorCode` on top of other `Error` properties to facilitate displaying of error dialogs.
- Various type changes from `GovWalletBalanceError` to `ErrorWithCodes`.
- Add translations for HTTP 50X errors. In particular, HTTP 500, 502, 503, and 504.
- Ability to display `ErrorWithCodes` errors
- HTTP 400 errors will be displayed with title as their error code, and description as error message.
- HTTP 50X errors will …
> feat(v1): error dialogs for HTTP 400 and 50X errors from GovWallet

- src/components/AlertModal/AlertModal.tsx
- src/components/CustomerQuota/CustomerQuotaScreen.test.tsx
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/hooks/useCart/useCart.test.tsx
- src/hooks/useCart/useCart.tsx
- src/services/quota/index.tsx
- src/services/quota/postTransaction.test.ts
- src/services/quota/quota.test.ts
[Notion link](https://www.notion.so/sally-wallet/Handling-timeout-when-Sally-calls-GovWallet-v2-customer-paynow-create-in-MINDEF-environment-Status--df04eb7102994ec9bf743f6147422717) 
This PR adds
- ability to throw out errors received from `/transactions/paynow` under services
- refactoring of all tests for `postTransactions` out to its own file
- add tests to test that the GovWallet errors are thrown out properly
- updates `_completeCheckout` in `useCart` so that we set the ErrorWithCodes as is
- add tests to ensure that useCart is showing the new errors properly
~- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow~
I've asked around and it seems that we have trouble writing the e2e tests, so I am not …
> feat: handle errors thrown by transactions/paynow

- src/components/CampaignInitialisation/CampaignInitialisationScreen.tsx
- src/components/CampaignLocations/CampaignLocationsScreen.tsx
- src/components/CustomerAppeal/CustomerAppealScreen.test.tsx
- src/components/CustomerAppeal/CustomerAppealScreen.tsx
- src/components/CustomerDetails/CollectCustomerDetailsScreen.test.tsx
- src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
- src/components/CustomerDetails/InputIdSection.tsx
- src/components/CustomerQuota/CustomerQuotaProxy.tsx
- src/components/CustomerQuota/CustomerQuotaScreen.tsx
- src/components/DailyStatistics/DailyStatisticsScreen.tsx
- src/components/DailyStatistics/StatisticsHeader.tsx
- src/components/Login/LoginContainer.test.tsx
- src/components/Login/LoginContainer.tsx
- src/components/Logout/LogoutScreen.test.tsx
- src/components/Logout/LogoutScreen.tsx
- src/components/MerchantPayout/MerchantPayoutScreen.tsx
- src/components/PayoutFeedback/PayoutFeedbackScreen.tsx
- src/navigation/Content.tsx
- src/navigation/CustomerQuotaStack/index.tsx
- src/navigation/MerchantPayoutStack/index.tsx
- src/types.ts
[Expo Upgrade](https://www.notion.so/sally-wallet/Chore-Upgrade-Expo-SDK-to-45-explore-Mobile-E2E-on-local-PR-env-86cee57ced264f6fbfb5cc8650ed8a1e) 
- type refactoring for expo-45-upgrade
- work in progress - yet to figure a way to navigate and pass params into `CustomerQuotaStack`. 
- usually navigate is to screen..?
- prob same issue for `MerchantPayoutStack`
> Chore: nav types refactoring

- src/services/helpers.ts
- src/services/quota/index.tsx
[Notion link](https://www.notion.so/sally-wallet/Aligning-timeouts-in-PayNow-API-calls-between-SupplyAlly-and-GovWallet-fac6ac4a0aa44b06aed8360e3395c224) 
- configurable timeout for PayNow create endpoint on Sally
- change timeout to 45
> feat: add configurable timeout in seconds for PayNow

- src/services/quota/index.tsx
[Notion link](https://www.notion.so/sally-wallet/Aligning-timeouts-in-PayNow-API-calls-between-SupplyAlly-and-GovWallet-fac6ac4a0aa44b06aed8360e3395c224) 
- change timeout from 45 to 30
> chore: update paynow api timeout to 30

- .github/workflows/deploy_branch_preview.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
[Notion link](https://www.notion.so/sally-wallet/03-Login-to-SupplyAlly-dashboard-via-Singpass-b1deaff4e6d84baaa43cca3f24ba0404) 
- latest binary version to be fetched before test step in production
> chore: get latestBinaryVersion before prod tests and deploy

- .github/workflows/deploy_prod.yml
[Notion link](https://www.notion.so/sally-wallet/03-Login-to-SupplyAlly-dashboard-via-Singpass-b1deaff4e6d84baaa43cca3f24ba0404) 
- add the getting of latest binary version in deploy prod step
> chore: add back getting of latest binary version in deploy prd step

- src/components/HelpModal/HelpModal.tsx
[Notion link](https://www.notion.so/sally-wallet/07-GovSupply-mobile-app-Redirect-Need-help-Help-Support-from-Zendesk-to-Isomer-landing-si-e964496535d74e4b99efb6df6a1742ba?d=67ec4aa6290f4de3a7f186236cedbcd3) 
- top margin, ensuring that we can click the exit icon (cross) in the help and support page 
**BEFORE**
**AFTER**
> style: margin top for ios to exit help & support

- src/components/HelpModal/HelpModal.tsx
[Notion link](https://www.notion.so/sally-wallet/GovSupply-s-App-Ask-a-question-Webapp-s-Help-Support-Link-to-govsupply_support-tech-gov-sg-a652da071d504e13a8b7ce4a2eda5118) 
This PR... 
- removes the window.location to direct them to their mail app
- splits `SUPPORT_URL` into `FAQ_SUPPORT_URL` and `SUPPORT_EMAIL_REF`
-  `FAQ_SUPPORT_URL` is used to render the webpage inside the webview when users click `Help and Support`
- `SUPPORT_EMAIL_REF` is used in the `onPressAskQuestion` function
> fix: redirection of GS email and webview render issue [SGW-4160]

- src/components/Login/utils.test.tsx
- src/components/Login/utils.ts
- src/services/auth/index.tsx
[Notion link
](https://www.notion.so/sally-wallet/OTA-Block-GovSupply-Mobile-Application-for-usage-Stage-1-only-3ecd085cfd3347d7920846a7739cff00)
https://github.com/rationally-app/mobile-application/assets/43963814/69cfcb1f-b0d3-4279-b05f-38caa27dc5c7
- Reverts rationally-app/mobile-application#789
- more sentry logs
> chore: revert changes to handle new and old QR formats + sentry logging [SGW-3617]

- src/components/Login/BlockUser.tsx
[Notion link](https://www.notion.so/sally-wallet/OTA-Block-GovSupply-Mobile-Application-for-usage-Stage-1-only-3ecd085cfd3347d7920846a7739cff00?d=7b93b8c98ca64e23a014bc0696216912#b77a63e08ff54ea6be261533cacb3e26) 
This PR... 
- fixes desk check but removing border of Continue to App button on soft blocking screen
> style: remove border for continue to app button on soft block screen [SGW-3617]
