scripts/commenter.sh
src/common/hooks/useConfig/index.tsx
src/common/styles/colors.tsx
src/common/styles/index.tsx
src/components/Credits/index.tsx
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Layout/AppName.tsx
src/components/Layout/Buttons/DangerButton.tsx
src/components/Layout/TopBackground.tsx
src/components/Login/LoginContainer.tsx
src/config/index.tsx
src/services/auth/auth.test.tsx
src/services/auth/index.tsx
src/services/quota/index.tsx
src/services/quota/quota.test.tsx

Allow the app to switch into staging network once the icon is long pressed for 5 seconds.

feat: Staging mode switch

---

src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Login/LoginContainer.tsx
src/context/products.tsx
src/navigation/index.tsx

Added products context to be populated during auth
Using getProduct from the context to get the product

feat: human readable names for products

---

package-lock.json
src/components/Credits/index.tsx
src/components/CustomerQuota/CustomerCard.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Layout/Checkbox.tsx
src/components/Layout/Header.tsx

- Tweak sizing of components
- Make CustomerQuotaScreen scrollable to handle the many items
- Updated packages recommended by npm audit fix

Work on CustomerQuotaScreen

---

src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Layout/Checkbox.tsx
src/context/products.tsx

Hello! 
What's in this PR:
- Added custom sorting logic (the order will be given from the backend in the `Name` key
- Styled the items again as the display name is now quite long
Do let me know if it is ok (:

Add sorting logic and edit styling

---

src/components/Layout/AppName.tsx
src/components/Login/LoginContainer.tsx

Creating a visible toggle, instead of a long press haha

Create visible toggle between modes

---

src/components/Layout/AppName.tsx
src/components/Login/LoginContainer.tsx

This reverts commit a0fdf56ff5ca92ec49872b467e35abeaca713a4f, reversing
changes made to d58b793db4c89f74b115c815f3b3651da729fafe.

Revert "Merge pull request #15 from rationally-app/feat/toggle-modes"

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Login/LoginContainer.tsx

* Ensure shadow of the customer card can be seen
* Remove input field from login screen, users must scan a QR.

feat: style updates

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerDetails/InputNricSection.tsx
src/utils/validateNric.test.tsx
src/utils/validateNric.tsx

Extracting out this part so that we can use it in modals and other screens

feat: add InputNricSection

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/CustomerQuota/ItemsSelectionCard.tsx
src/components/CustomerQuota/NoQuotaCard.tsx
src/components/CustomerQuota/PurchaseSuccessCard.tsx
src/components/CustomerQuota/sharedStyles.tsx
src/components/CustomerQuota/types.ts

Move checking of quota to `CustomerQuotaScreen` so we don't depend on `CollectCustomerDetailsScreen` to pass it through state (separation of concerns).
Also split `CustomerQuotaScreen` into smaller components as it was getting very long

feat: check quota in quota screen

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/AddUserModal.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx

Some ScrollViews have the problem where the scrollbar appears in the middle of the screen and not flushed to the right.

fix: iOS scrollbar position

---

src/components/CustomerQuota/ItemsSelection/ItemContent.tsx
src/hooks/useCart/useCart.test.tsx
src/hooks/useCart/useCart.tsx

* Use default quota
* Ensure empty description is not rendered

fix: default quota

---

package-lock.json
package.json
src/components/Credits/index.tsx
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/CustomerQuota/sharedStyles.tsx
src/components/FeatureToggler/FeatureToggler.tsx
src/components/HelpModal/HelpModal.tsx
src/components/Layout/Buttons/HelpButton.tsx
src/components/Login/LoginContainer.tsx
src/context/help.tsx
src/flags.ts
src/navigation/index.tsx

* WebView to show zendesk support modal
* Modal can be opened from any screen
* Can be navigated (back and forward buttons)
* Android back button works within the WebView and pressing physical back when there's no more back closes the modal
* Includes 'Ask a question' button that directly goes to the submit request page (it's hidden in a hamburger menu)
* Add feature flags to switch this off for now

feat: help modal

---

src/components/CustomerQuota/PurchaseSuccessCard.tsx
src/components/CustomerQuota/types.ts
src/components/CustomerQuota/utils.test.ts
src/components/CustomerQuota/utils.ts
storybook/stories/CustomerQuota/PurchaseSuccessCard.tsx
storybook/stories/index.tsx

feat: update PurchaseSuccessCard to show quantities broken down by id

---

.circleci/config.yml

Have added both account details into circle ci haha

update config.yml to push to both expo accounts

---

src/hooks/useCart/useCart.tsx

[Trello card](https://trello.com/c/OcRVdqLx/102-bug-auto-select-of-vouchers-happens-intermittently)
This MR fixes the item checkbox so that it is always checked on load of item selection page if the item default quantity is 1.
Previously it was not checked for the first few times of loading the item selection page as we performed merging of quota response from backend with the cart before the policies were loaded into the context.

fix: item checkbox default checked when default quantity is 1

---

src/components/CustomerQuota/CheckoutSuccess/RedeemedItem.tsx
src/components/CustomerQuota/ItemsSelection/Item.tsx
src/components/CustomerQuota/ItemsSelection/ItemCheckbox.tsx
src/components/CustomerQuota/ItemsSelection/ItemIdentifiersCard.tsx
src/components/CustomerQuota/NoQuotaCard.tsx
src/components/CustomerQuota/types.ts
src/components/CustomerQuota/utils.test.ts
src/components/CustomerQuota/utils.ts
src/hooks/useCart/useCart.test.tsx
src/hooks/useCart/useCart.tsx
src/services/policies/index.ts
src/services/quota/index.tsx
src/types.ts
storybook/stories/CustomerQuota/CheckoutSuccessCard.tsx

This PR
* Updates policy identifiers to new shape
* Renames quota and transaction identifiers as identifierInputs for better differentiation
* Adds types to identifier inputs
(Test against [pr33](https://github.com/rationally-app/backend-api/pull/33))

chore: update policy identifiers

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx

[trello](https://trello.com/c/UDzUoDrj)
fix bug where keyboard remains shown when camera launched

fix: (bug) dismiss keyboard when camera shown

---

src/components/CustomerQuota/NoQuotaCard.tsx

adding brackets to account for singular and plural items. i.e. Item(s)

style: use brackets for plural items

---

src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/CheckoutSuccess/checkoutMessages.ts
src/components/CustomerQuota/ItemsSelection/ItemNoQuota.tsx
src/components/CustomerQuota/NoQuotaCard.tsx

Forgot a few places where we were doing checks against lowercase policy type!!! hehehe oops

fix: policy type is now uppercase

---

src/components/MerchantPayout/AllValidVouchersModal.tsx
src/components/MerchantPayout/MerchantPayoutScreen.tsx
src/components/MerchantPayout/VoucherInputSection.tsx

This PR includes:
-  all valid vouchers modal
Trello Link:
https://trello.com/c/IOpEMC95/150-allvalidvouchersmodal

feat: added all valid vouchers modal

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/AddUserModal.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/CustomerQuota/ItemsSelection/ItemIdentifier.tsx

[trello](https://trello.com/c/rkLayD69)
Super quick fix to replace "Dismiss" to "OK" for button label when error/alert is thrown
also realised there was a typo all along?? "Dimiss" haha

style: replace error button label from dismiss with OK

---

.eslintrc.js
src/components/Layout/ModalwithClose.tsx
src/components/Login/LoginOTPCard.tsx
src/components/MerchantPayout/AllValidVouchersModal.tsx
src/components/MerchantPayout/MerchantPayoutScreen.tsx
src/components/MerchantPayout/ValidVoucherCount.tsx
src/components/MerchantPayout/VoucherInputSection.tsx
src/components/MerchantPayout/VoucherStatusModal/InvalidCard.tsx
src/components/MerchantPayout/VoucherStatusModal/VoucherStatusModal.tsx
src/components/VoucherScanner/ManualAddVoucherModal.tsx
src/components/VoucherScanner/VoucherScanner.tsx
src/navigation/Content.tsx
src/utils/validateVoucherCode.tsx

This PR include:
- Shifting of UI according to Figma
- adding to lint boolean rule
- fixing voucher scanner back handler functionality

feat: merchant UI edits

---

src/components/MerchantPayout/MerchantPayoutScreen.tsx
src/components/PayoutFeedback/PayoutFeedbackScreen.tsx
src/navigation/MerchantPayoutStack/PayoutFeedbackScreen.tsx
src/navigation/MerchantPayoutStack/index.tsx

This PR includes:
- adding of PayoutFeedbackScreen
Trello Link:
https://trello.com/c/JUJIoF6L/151-payoutfeedbackscreen

feat: added payout feedback screen

---

src/components/Login/LoginContainer.tsx
src/components/Login/LoginOTPCard.tsx
src/components/PayoutFeedback/PayoutFeedbackScreen.tsx

[trello](https://trello.com/c/3i74wCKH)

feat: fetch version and features during redirect

---

src/hooks/useVoucher/useVoucher.test.tsx
src/utils/validateMerchantCode.test.tsx
src/utils/validateMerchantCode.tsx

8 max limit alphanumeric (means if they enter 6 characters can go through too)

feat: update merchant code validation

---

src/hooks/useCheckVoucherValidity/useCheckVoucherValidity.test.tsx
src/utils/validateVoucherCode.tsx

Based on the discussion on slack, we'll update it to: 
"Please check that the voucher code is in the correct format"
In future, we will use concept of `ID_VALIDATION` to control the validation type so it can be controlled by feature flags/dist env.

chore: update voucher code validation error

---

.github/workflows/deploy_prod.yml
README.md

This PR includes:
- renaming or steps in prod release process

chore: improving ci-cd process

---

src/components/MerchantPayout/MerchantPayoutScreen.tsx
src/components/MerchantPayout/VoucherStatusModal/VoucherStatusModal.tsx
src/components/VoucherScanner/VoucherScanner.tsx
src/hooks/useCheckVoucherValidity/useCheckVoucherValidity.tsx

https://www.notion.so/Merchant-flow-dialogs-e7ec131e72cc40e0abab034ad8397e02

chore: merchant flow dialog standardisation

---

src/components/MerchantPayout/VoucherStatusModal/InvalidCard.tsx
src/components/MerchantPayout/VoucherStatusModal/VoucherStatusModal.tsx
src/hooks/useCheckVoucherValidity/useCheckVoucherValidity.tsx
src/utils/validateMerchantCode.tsx
src/utils/validateNric.tsx
src/utils/validateVoucherCode.test.tsx
src/utils/validateVoucherCode.tsx

Blocked by #107 
* This pertains to the merchant flow
* Sets a limit at maximum 200 vouchers per transaction
https://www.notion.so/Limit-to-max-200-vouchers-scanned-1927dbbdd886469995727081816b49d7

feat: scanning limit

---

src/components/Login/LoginContainer.tsx

Use this to generate the URLs: https://kitkm.csb.app?releaseChannel=pr110

feat: use queryparams from deeplinks

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerDetails/InputIdSection.tsx
src/components/CustomerQuota/AddUserModal.tsx

undefined is possibly passed as keyboard type previously.
condition is now used in parent component to ensure specific keyboard type is passed

fix: undefined id keyboard type

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/AddUserModal.tsx

Handle case when features property values are accessed when features is undefined
e.g. `features.id.type` when `features` is undefined

fix: handle features props undefined

---

App.tsx
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/Login/LoginContainer.tsx
src/components/Login/LoginOTPCard.tsx
src/hooks/useCart/useCart.tsx
src/hooks/useCheckUpdates.tsx
src/services/auth/auth.test.tsx
src/services/auth/index.tsx
src/services/envVersion/envVersion.test.tsx
src/services/envVersion/index.ts
src/services/quota/index.tsx
src/services/quota/quota.test.tsx
src/utils/errorTracking.ts

where we mock it on dev so we can see what is being called during development

refactor: move sentry out to its own module 

---

src/components/CustomerQuota/CheckoutSuccess/RedeemedItem.tsx

Displays quantity for checkout if identifierInput does not exist. This is mainly for the FFTH distribution. It will affect those distributions of type "REDEEM".

feat: display quantity for checkout if no identifierinput

---

src/components/Layout/Stepper.tsx

Thanks @Gabrieltay for the idea!!

fix: user checkout stale cart

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerDetails/InputIdSection.tsx
src/hooks/useCheckVersion/useCheckVersion.test.tsx
src/services/campaignConfig/campaignConfig.test.ts
src/services/campaignConfig/campaignConfig.ts
src/types.ts

Utilises the `campaignName` property in campaign config features

feat: campaign name

---

src/components/CustomerQuota/CustomerQuotaScreen.tsx

invalid phone number case was not account for, end up throwing to error boundary

fix: add missing phone number case, typo for tokens

---

src/components/CustomerQuota/NoQuotaCard.tsx

Update date format [`DD MMM YYYY, HH:MM(AM or PM)`]on `NoQuota` card 
https://www.notion.so/Changing-date-format-on-Limit-Reached-screen-f47fa5d5328d47df926728722e7dca2d

feat: update date format in limit reached screen

---

src/components/Login/LoginContainer.tsx
src/components/Login/utils.test.tsx
src/components/Login/utils.ts
src/context/alert.tsx

feat: finalise QR error messages

---

src/navigation/Content.tsx
src/navigation/OutdatedAppScreen.tsx

feat: add outdated app screen

---

src/components/AlertModal/AlertModal.tsx
src/context/alert.tsx
storybook/stories/Modals/Alert.tsx

feat: styling updates for alert with no description

---

src/components/CustomerAppeal/ReasonSelection/ReasonItem.tsx
src/components/CustomerAppeal/ReasonSelection/ReasonSelectionCard.tsx

To remove horizontal paddings
**Before**
**After**

fix: reason padding

---

src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx

Also includes: different alert modals for different add user error types

fix: add user modal bug

---

src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/NoQuotaCard.tsx
src/components/CustomerQuota/NotEligibleCard.tsx
src/components/CustomerQuota/sharedStyles.tsx
src/components/PayoutFeedback/PayoutFeedbackScreen.tsx

feat: change emojis on feedback screens to thumbs up/down icons

---

src/components/CustomerQuota/ItemsSelection/Item.tsx
src/hooks/useCart/useCart.test.tsx
src/hooks/useCart/useCart.tsx

Bug: when checkout limit is 1, upon toggle of itemCheckBox on checkout, the quantity will be change to maxQuantity

fix: bug fix for checkoutLimit

---

src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/CustomerQuota/NoQuotaCard.tsx
src/hooks/useCart/useCart.tsx
src/types.ts
storybook/stories/CustomerQuota/CheckoutSuccessCard.tsx

See [this](https://www.notion.so/When-usage-policy-is-applied-allow-users-to-see-the-balance-of-the-global-limit-on-the-Redeemed-scr-933050c1174d4fa3bb539541796f64fe) and [this](https://www.notion.so/When-usage-policy-is-applied-allow-users-to-see-the-balance-of-the-global-limit-on-the-Limit-Reache-88fe995b61b24f74a3a93be30cec8609#be6a6e029f4646d78b1970a0c88c5049).
This PR is related to added global limit messages to notify users when usage policy is set.

feat: usage policy global limit messages

---

src/components/CampaignInitialisation/CampaignInitialisationScreen.tsx
src/components/CampaignLocations/CampaignLocationsListItem.tsx
src/components/CampaignLocations/CampaignLocationsScreen.tsx
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/Layout/Buttons/DarkButton.tsx
src/components/Layout/Buttons/SecondaryButton.tsx
src/components/Layout/InputWithLabel.tsx
src/components/Layout/PhoneNumberInput.tsx
src/components/Loading/index.tsx
src/components/Login/LoginContainer.tsx
src/components/Login/LoginMobileNumberCard.tsx
src/components/Login/LoginOTPCard.tsx
src/components/MerchantPayout/AllValidVouchersModal.tsx
src/components/MerchantPayout/MerchantPayoutScreen.tsx
src/components/MerchantPayout/VoucherInputSection.tsx
src/context/authStore.test.tsx
src/context/authStore.tsx
src/context/campaignConfigsStore.test.tsx
src/context/campaignConfigsStore.tsx
src/context/config.tsx
src/hooks/useLogout.tsx
src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.test.tsx
src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.tsx
src/navigation/Content.tsx
src/navigation/CustomerQuotaStack/index.tsx

TODO
- ~~Handle session expiry properly => should remove the auth credentials rather than remove all credentials~~ Will remove this feature for now

feat: multiple campaigns

---

.eslintrc.js
src/components/CampaignLocations/CampaignLocationsListItem.tsx
src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/CheckoutSuccess/PurchasedItem.tsx
src/components/CustomerQuota/CheckoutSuccess/RedeemedItem.tsx
src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
src/components/CustomerQuota/NoQuota/TransactionTitle.tsx
src/components/ErrorBoundary/ErrorBoundary.tsx
src/components/MerchantPayout/VoucherStatusModal/VoucherStatusModal.tsx
src/components/PayoutFeedback/PayoutFeedbackScreen.tsx
src/utils/dateTimeFormatter.test.ts
src/utils/dateTimeFormatter.ts
storybook/stories/ErrorBoundary/ErrorBoundary.tsx

Also:
chore: add eslint rule to ensure no duplicate imports

refactor: extract datetime formatter to keep date format consistent

---

src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/NoQuota/NoQuotaCard.test.ts
src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
src/hooks/usePastTransaction/usePastTransaction.test.tsx
src/hooks/usePastTransaction/usePastTransaction.tsx

This PR adds
* Spinner for checkout and no quota screens while past transactions are being fetched
* Error alert box for checkout screen when fetching past transactions fails

feat: loader for past transactions, error alert for checkout

---

src/utils/getIdentifierInputDisplay.test.ts
src/utils/getIdentifierInputDisplay.ts

https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=ac4bea97a253457b9ba10a4381bb6a70

chore: reverted masking of phone numbers

---

package-lock.json
package.json

to cover cases of phone numbers 803xxxxxx haha

chore: update google-libphonenumber

---

src/hooks/usePastTransaction/usePastTransaction.tsx

Mask sensitive data on sentry!

fix: mask sensitive data on sentry

---

run/.expo/settings.json
src/components/CampaignLocations/CampaignLocationsScreen.tsx

When you add campaigns and go to campaign screen, the campaigns will be in alphabetical order.

feat: Ordering multiple campaigns in alphabetic order

---

src/utils/validateIdentifierInputs.test.ts

fix some tests that was broken due to newer copy change PRs being merged in

tests: validateIdentifierInputs tests

---

src/components/AlertModal/AlertModal.tsx
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerDetails/InputIdSection.tsx
src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierPhoneNumberInput.tsx
src/components/CustomerQuota/ItemsSelection/IdentifierLayout/IdentifierTextInput.tsx
src/components/CustomerQuota/ItemsSelection/ItemCheckbox.tsx
src/components/CustomerQuota/ItemsSelection/ItemContent.tsx
src/components/CustomerQuota/ItemsSelection/ItemNoQuota.tsx
src/components/CustomerQuota/ItemsSelection/ItemStepper.tsx
src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx
src/components/CustomerQuota/NoQuota/AppealButton.tsx
src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
src/components/CustomerQuota/NotEligibleCard.tsx
src/components/IdScanner/IdScanner.tsx
src/components/Layout/AppHeader.tsx
src/components/Layout/Buttons/BaseButton.tsx
src/components/Layout/Buttons/DangerButton.tsx
src/components/Layout/Buttons/DarkButton.tsx
src/components/Layout/Buttons/SecondaryButton.tsx
src/components/Layout/Buttons/TransparentButton.tsx
src/components/Layout/DrawerNavigation.tsx
src/components/Layout/InputWithLabel.tsx
src/components/Layout/PhoneNumberInput.tsx
src/components/Layout/Stepper.tsx
src/components/Login/LoginMobileNumberCard.tsx
src/components/Login/LoginOTPCard.tsx
src/context/drawer.tsx

[Notion link](https://www.notion.so/Testing-Add-essential-accessibility-IDs-3c0fd1ebab2041a5b0312664b7299000)
This PR adds accessibility labels for the components used in our existing e2e tests. Added [a guide for adding accessibility ids on Notion](https://www.notion.so/How-to-add-Accessibility-IDs-5c51008278b64fb5ab1ea6b66958dd56).

chore: add accessibility labels

---

src/common/styles/typography.tsx

This PR removes an unnecessary `console.log` from `typography.tsx`.

hotfix: removed console.log from typography.tsx

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/NoQuota/AppealButton.tsx
src/components/DailyStatistics/StatisticsHeader.tsx
src/components/DailyStatistics/TitleStatistic.tsx
src/components/DailyStatistics/TransactionHistoryCard.tsx
src/components/PayoutFeedback/PayoutFeedbackScreen.tsx

Added Accessibility IDs
Checked against UIAutomator
-redeemedLimitReached
-Statistics Screen
-no items scanned
-chevron-left
-back
-statistics (Statistics Header)

feat: add more accessibility ID

---

src/common/i18n/translations/en.ts

Related to: https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=c164596507ac48d28153524e72c50b15

feat: words for FrontEnd v2 Standardization Revised copy

---

src/types.ts
src/utils/validateIdentification.ts

~I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components~
~I've added/updated unit/integration tests~
~I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow~
~I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)~
~I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)~

feat: add UIN validation option

---

src/common/styles/colors.tsx
src/components/Layout/TopBackground.tsx

https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=aab35e10a0d84dffb1fbb9f29ed3ba5b

feat: color palette v2 and grey color updates

---

.github/workflows/test_e2e.yml

Added env var for pcloudy in e2e_test.yml file

chore: set pcloudy env var for tests

---

src/components/CustomerQuota/CheckoutSuccess/CheckoutSuccessCard.tsx
src/components/CustomerQuota/NoQuota/NoQuotaCard.tsx
src/components/CustomerQuota/NotEligibleCard.tsx

[Notion link](https://www.notion.so/Return-TT-Token-FrontEnd-Changes-69860c2451a94f89bba3c9fa34ac02f9) 
- refactor some i18nt translation to use c13nt
- replace smelly types

chore: refactor some translations to use c13nt

---

src/common/i18n/translations/en.ts
src/common/i18n/translations/type.ts
src/common/i18n/translations/zh.ts
src/components/CustomerQuota/CheckoutUnsuccessful/CheckoutUnsuccessfulCard.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx

[Notion link](https://www.notion.so/Return-TT-Token-FrontEnd-Changes-69860c2451a94f89bba3c9fa34ac02f9) 
- updated i18nt translations for checkoutSuccessCard and checkoutUnsuccessfulCard
- add CheckoutUnsuccessfulCard component

feat: implement unsuccessful checkout card component

---

src/components/Login/LoginMobileNumberCard.tsx

chore: add space below login mobile number input

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx

[Notion link](https://www.notion.so/Hide-scanner-after-successful-scanning-of-ID-77239aff2ecc4a6abda773b8182e4e4c)

perf: ensure camera is removed on navigating to customer quota screen

---

jest.config.js
package-lock.json
package.json
src/context/authStore.test.tsx
src/context/campaignConfigsStore.test.tsx
src/hooks/useCart/useCart.test.tsx
src/hooks/useCheckVoucherValidity/useCheckVoucherValidity.test.tsx
src/hooks/useDailyStatistics/useDailyStatistics.test.tsx
src/hooks/useUpdateCampaignConfig/useUpdateCampaignConfig.test.tsx
src/hooks/useVoucher/useVoucher.test.tsx

[Notion link](https://www.notion.so/update-testing-library-react-native-to-v7-2-0-1fb9b885bba94e779c651d5fa54202b5) 
- updates `@testing-library/react-native` to v7.2.0
- migrate unit test cases to v7.2.0 (replace `wait` to `waitFor`

chore: update @testing-library/react-native to latest v7.2.0

---

src/components/IdScanner/IdScanner.tsx
src/components/IdScanner/IdScannerLabel.tsx

[Notion link](https://www.notion.so/Update-policy-to-charge-lost-TT-Tokens-if-it-s-lost-for-a-2nd-time-Enter-Payment-receipt-number-28a3cb5dfdbc4e9e95a21a1b1490db0a) 
This PR adds the code128 in IdScanner

feat: add code128 in IdScanner

---

src/components/CustomerQuota/CustomerQuotaScreen.tsx

This PR adds Sentry events for some checkout failures

chore: capture invalid/duplicate identifier inputs on Sentry

---

src/components/Login/LoginMobileNumberCard.test.tsx
src/components/Login/LoginOTPCard.test.tsx
src/components/Login/LoginScanCard.test.tsx
src/test/helpers/providers.tsx

[Notion link](https://www.notion.so/Frontend-2dcbb8ad3f234aee98d5f289d3170b40#f01038cb652e426fa36ce23b38238fa8) 
- Component testing using @testing-library/react-native
- Unit tests for `LoginMobileNumberCard`, `LoginOTPCard`, and `LoginScanCard`

feat(tech debt): FE components testing

---

jest.config.js
jest.setup.ts
package-lock.json
package.json

- `jest-expo` preset 
- remove unnecessary `@expo` mocks

chore: add jest-expo preset

---

.github/workflows/test_e2e.yml

Added e2e env vars : 
1. E2E_APP_ACCOUNT
2. E2E_RELEASE_CHANNEL

added e2e env vars

---

jest.setup.ts
src/components/CustomerDetails/CollectCustomerDetailsScreen.test.tsx
src/components/CustomerDetails/InputIdSection.test.tsx
src/components/CustomerDetails/ManualPassportInput.test.tsx
src/test/helpers/providers.tsx

- components testing for CollectCustomerDetailsScreen
- updates `jest.setup.ts` to also mock react native `Vibrate` module
- add `<any>` type for test helper

chore: customer details components testing

---

src/components/DailyStatistics/DailyStatisticsScreen.test.tsx
src/components/DailyStatistics/TitleStatistic.test.tsx
src/components/DailyStatistics/TitleStatistic.tsx
src/components/DailyStatistics/TransactionHistoryCard.test.tsx

- components testing for DailyStatistics folder

chore: add component testing for statistic screen

---

src/components/CustomerAppeal/CustomerAppealScreen.test.tsx
src/components/CustomerAppeal/ReasonSelection/ReasonItem.test.tsx
src/components/CustomerAppeal/ReasonSelection/ReasonSelectionCard.test.tsx
src/components/CustomerAppeal/ReasonSelection/ReasonSelectionHeader.test.tsx
src/test/helpers/providers.tsx

- components testing for Customer Appeal directory

chore(tech debt): testing components in CustomerAppeal

---

src/common/styles/index.tsx
src/components/CustomerQuota/ItemsSelection/ItemMaxUnitLabel.tsx
src/components/CustomerQuota/ItemsSelection/sharedStyles.tsx

[Notion link](https://www.notion.so/Enlarge-quota-limit-font-size-0e10b1384e33495e886536392958fc50) 
- change `Max` to `Max.`
- update `sharedStyle.maxQuantityLabel`

feat: Enlarge quota limit font size

---

src/components/CustomerDetails/ManualPassportInput.tsx
storybook/stories/CustomerAppeal/ReasonSelectionCard.tsx
storybook/stories/CustomerDetails/index.tsx
storybook/stories/CustomerQuota/CheckoutSuccessCard.tsx
storybook/stories/CustomerQuota/CheckoutUnsuccessful.tsx
storybook/stories/DailyStatistics/StatisticsHeader.tsx
storybook/stories/DailyStatistics/index.tsx
storybook/stories/Layout/Checkbox.tsx
storybook/stories/Layout/Dropdown.tsx
storybook/stories/Layout/InputWithLabel.tsx
storybook/stories/Layout/LightBox.tsx
storybook/stories/Layout/ModalWithClose.tsx
storybook/stories/Layout/PhoneNumberInput.tsx
storybook/stories/Layout/index.tsx
storybook/stories/decorators/index.tsx
storybook/stories/index.tsx

[Notion link](https://www.notion.so/FE-Storybook-35a2cbde477a4bdc92fddb5449c5ec57) 
- add the storybook of molecules level 
1.InputWithLabel
2.LightBox
3.ModalWithClose
4.CustomerDetails InputSelection
5.CustomerDetails InputIdSection
6.CustomerDetails ManualPassportInput
7.CheckoutSuccess PurchasedItem
8.CheckoutSuccess RedeemedItem
9.DropdownFilterInput
10.DropdownFilterModal
11.Statistics StatisticsHeader
12.Statistics TitleStatistic
13.Statistics TransactionHistoryCard

feat: added the storybook of molecules level

---

src/components/CustomerQuota/ItemsSelection/ItemContent.tsx
src/components/CustomerQuota/ItemsSelection/ItemStepper.tsx

Eida is writing the notion story for this
- move all labels to the left in accordance with the style guide

chore: move labels to the left

---

src/components/CustomerQuota/ItemsSelection/sharedStyles.tsx

[Notion link](https://www.notion.so/Enlarge-quota-limit-font-size-0e10b1384e33495e886536392958fc50) 
- replace max quantity label style to `brand-regular` instead of `brand-italic`

refactor: enlarge quota limit style

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx

- replace check barcode logic to check scannerIdType label

hotfix: wrong condition logic

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx

- remove scannerType===None logic

chore: to allow manual entry

---

src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx

- adds `event.data = passportId ?? ""` to catch undefined error

chore: check if passportId is undefined

---

src/components/CustomerQuota/CustomerQuotaScreen.test.tsx

- component testing for customerQuotaScreen

feat: add customerQuotaScreen component testing

---

src/common/i18n/translations/zh.ts
src/hooks/useDailyStatistics/utils.ts

[Notion link](https://www.notion.so/Chinese-translation-for-app-Redemption-Statistics-1cbd66b827b74892a1d072109b438a47)

fix: appeal translation

---

src/components/IdScanner/IdScanner.tsx

- add scan bypass if device is using emulator

chore: add bypass check for android emulator

---

src/components/CustomerQuota/CustomerQuotaScreen.test.tsx
src/components/CustomerQuota/CustomerQuotaScreen.tsx
src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx
src/hooks/useCart/useCart.test.tsx
src/hooks/useCart/useCart.tsx

[Notion link](https://www.notion.so/Sequence-of-flow-for-Payment-collected-dialog-box-and-error-dialog-box-6702ba3744e84ab3b99153e5914326cc) 
- separate checkoutConfirmation and add PENDING_CONFIRMATION state
- add useEffect in `ItemsSelectionCard` to check whether cartState is `PENDING_CONFIRMATION`

feat: payment sequence flow

---

.github/workflows/deploy_prod.yml

[Notion link](https://www.notion.so/9c31016e9e8e4fd0adf317e181f07082) 
- update `deploy_prod.yml` to use `github-slug-action@v3.x` instead

build: update github-slug-action from @v2.x to @v3.x

---

storybook/stories/Login/LoginContainer.tsx
storybook/stories/Login/index.tsx

- added the story book of login screen

feat: added storybook of login screen

---

__mocks__/@react-native-async-storage/async-storage.js
jest.config.js
jest.setup.ts
package-lock.json
package.json
src/context/authStore.test.tsx
src/context/authStore.tsx
src/context/campaignConfigsStore.test.tsx
src/context/campaignConfigsStore.tsx
src/context/config.tsx
src/hooks/useCheckUpdates.tsx
src/hooks/useTranslate/useTranslate.test.tsx
src/modules.d.ts

[Notion link](https://www.notion.so/fix-Deprecated-AsyncStorage-b4bf74451ecf41b6b65c4facd67b6e83) 
- replace deprecated react native async storage

build: update deprecated reactnative/async storage package

---

.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml

- increase max_old_space_size to deploy_prod and deploy_staging

build: add max old space size to deploy prod and staging

---

src/hooks/useCart/useCart.test.tsx
src/hooks/useCart/useCart.tsx
src/utils/cleanIdentifierInputs.test.ts
src/utils/cleanIdentifierInputs.ts
src/utils/validateIdentifierInputs.ts
src/utils/validateInputWithRegex.test.tsx
src/utils/validateInputWithRegex.ts

Reverts rationally-app/mobile-application#407

Revert "Revert "fix: validate regex input for leading and trailing whitespaces""

---

src/components/Layout/Checkbox.tsx

[Notion link](https://www.notion.so/sally-wallet/Fix-TT-Token-s-Related-history-accordion-misalignment-d6fbaa2b403e4eeca1a51cdf308bf255) 
- fix the [Desk check](https://www.notion.so/sally-wallet/Fix-TT-Token-s-Related-history-accordion-misalignment-d6fbaa2b403e4eeca1a51cdf308bf255#d58f9cd6f0af468cab24924c315ccf0d) behaviour..
- fix the checkbox TouchableHighlight, previously anyever on the checkBox outer layout can selected/unselected now we more constrain the `TouchableHighlight` within the Icon layout - [layout diagram](https://www.notion.so/sally-wallet/Fix-TT-Token-s-Related-history-accordion-misalignment-d6fbaa2b403e4eeca1a51cdf308bf255#9810d2927620436180c38a29e751ae9b)

fix: checkbox TouchableHighlight

---

src/components/Layout/Checkbox.tsx

[Notion link](https://www.notion.so/sally-wallet/Fix-TT-Token-s-Related-history-accordion-misalignment-d6fbaa2b403e4eeca1a51cdf308bf255) 

fix: add accessibilityLabel in checkbox

---

src/utils/validatePhoneNumbers.test.tsx
src/utils/validatePhoneNumbers.tsx

[Notion link](https://www.notion.so/sally-wallet/Change-Regex-for-TT-Token-s-SG-Contact-number-from-lib-to-formsg-40c7136bf21a4853bb123046d4ac5fca) 
- change phone number validation for SG number to use more generic regex

feat: SG number uses regex

---

src/components/CustomerQuota/NoQuota/TransactionTitle.tsx

- fix for incorrect formatting of `time` vs `dateTime`

fix: copy changes, formatting of incorrect time

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
README.md
package-lock.json
package.json

This PR adds linting for our markdown files in the root project directory.
Added for backend v2 in https://github.com/rationally-app/backend-api/pull/1769.

docs: markdown lint

---

src/types.ts

[Notion link](https://www.notion.so/sally-wallet/Tech-Planning-Sprint-21-38288ba757cf4977a050ca4cdab4d368#549de18912b54de1a2eacee800360be6) 
* Updated features config because it was wrong
* Reordered everything by alphabetical order because OCD

chore: update config type

---

src/components/IdScanner/IdScanner.tsx
src/components/Layout/Buttons/DarkButton.tsx
src/components/Layout/PhoneNumberInput.tsx
src/components/Login/LoginContainer.test.tsx
src/components/Login/LoginMobileNumberCard.test.tsx
src/components/Login/LoginMobileNumberCard.tsx
src/components/Login/LoginOTPCard.test.tsx
src/components/Login/LoginOTPCard.tsx
src/components/Login/LoginScanCard.tsx

[Notion link](https://www.notion.so/sally-wallet/Integration-tests-LoginContainer-8577212106b14ffc81d3cc13c5efb0ed)
This PR adds unit test for loginContainer.

feat: add loginContainer unit test

---

storybook/stories/CustomerAppeal/CustomerAppealScreen.tsx

[PTSALLY - MPT-M002 NRIC in JavaScript](https://www.notion.so/sally-wallet/PT-SALLY-MPT-M002-NRIC-in-JavaScript-source-code-Storybook-ad5826fd853741f4860a763c46ff2e0b)
- change data display on storybook

fix(storybook): refactor customer appeal display

---

src/common/i18n/translations/zh.ts
src/components/Login/LoginContainer.test.tsx
src/components/Login/LoginContainer.tsx
src/context/alert.tsx

[Notion link](https://www.notion.so/sally-wallet/Bug-PT-SALLY-MPT-M001-URL-redirection-via-QR-code-3c3435d6d1e74ff59561bef80c92e3af) 
- handle `NetworkError` in `LoginContainer`
- `NetworkError` to have its own alert 
- Fix chinese translation for `systemErrorConnectivityIssues`

fix: invalid login QR domain network error

---

src/common/i18n/translations/en.ts
src/common/i18n/translations/zh.ts

[Notion link](https://www.notion.so/sally-wallet/Handling-timeout-when-Sally-calls-GovWallet-v2-customer-paynow-create-in-MINDEF-environment-Status--df04eb7102994ec9bf743f6147422717) 
This PR
- updates the english copy for network error
- updates the chinese copy for network error

feat(i18n): update text copy for network error

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/test_development_environment.yml

This PR speeds up the CICD workflow for on pull request env

chore(github-workflow): speed up cicd workflow for on pull request env

---

src/components/CustomerQuota/CustomerQuotaScreen.tsx

[Notion link](https://www.notion.so/sally-wallet/Improve-transaction-timing-between-GovWallet-Sally-f95cc2f71df647c89203ff5fa5067bf0) 
- Show spinner while awaiting response when getting GovWallet balance

refactor(govwallet): show spinner while fetching balance

---

package.json

chore: add typecheck script

---

src/hooks/govwallet/useGovWalletBalance/useGovWalletBalance.test.tsx
src/hooks/govwallet/useGovWalletBalance/useGovWalletBalance.tsx
src/services/govwallet/balance/balance.test.tsx
src/services/govwallet/balance/index.tsx
src/test/helpers/defaults.tsx
src/types.ts

[Notion link](https://www.notion.so/sally-wallet/Enhance-Sally-calling-GW-code-to-make-it-generic-d3a4acc824634cd4a68bf00fad7c8632) 
This PR adds dynamic govwallet balance matching

feat: dynamic govwallet balance matching

---

src/common/i18n/translations/en.ts
src/common/i18n/translations/type.ts
src/common/i18n/translations/zh.ts
src/components/ErrorBoundary/ErrorBoundaryContent.test.tsx
src/components/ErrorBoundary/ErrorBoundaryContent.tsx
src/navigation/Content.tsx

[Notion link](https://www.notion.so/sally-wallet/Technical-spike-Audit-finding-for-Secure-Coding-Standards-not-implemented-for-Mobile-Application-Ob-69dbd0f10dd14a6d8ddeaeef75b83a2e) 
This PR is 1 part of the above notion story. This adds rooted/jailbroken device detection via expo's [Device.isRootedExperimentalAsync](https://docs.expo.dev/versions/latest/sdk/device/#deviceisrootedexperimentalasync), and updates `ErrorBoundaryContent` component to handle such events.

feat: prevent rooted jailbroken devices

---

src/common/i18n/translations/en.ts
src/common/i18n/translations/type.ts
src/common/i18n/translations/zh.ts
src/context/alert.tsx

[Notion link](https://www.notion.so/sally-wallet/Allow-deduction-of-GW-credits-from-different-bank-accounts-for-NS-Home-Team-voucher-redemption-e49c670aa6c64fa8b992b46cae88c0c1?d=f1b2f433103243a6ac70d1d831c82b43#f7163400bf994328bfe454ddd3619a10) 
- Change title of dialog box when customer does not exist in campaign.
- _Original_: "Invalid customer Id"
- _New_: "Invalid identity"

refactor: title of govwallet invalid identity dialog

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
.github/workflows/test_e2e.yml

[Updating GHA Ubuntu version to latest for affected repos](https://www.notion.so/sally-wallet/Updating-GHA-Ubuntu-version-to-latest-for-affected-repos-1bfb3412c8bb4024a2de06ae82d86b90) 
- change `ubuntu-18.04` to `ubuntu-latest`

chore: update 18.04 to latest

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
package.json
src/components/CustomerDetails/CollectCustomerDetailsScreen.tsx
src/components/Login/LoginContainer.test.tsx
storybook/stories/CampaignLocationScreen/index.tsx
storybook/stories/CustomerAppeal/CustomerAppealScreen.tsx
storybook/stories/CustomerDetails/CustomerDetailsScreen.tsx
storybook/stories/DailyStatistics/DailyStatisticsScreen.tsx
storybook/stories/DailyStatistics/StatisticsHeader.tsx
storybook/stories/Layout/AppHeader.tsx
storybook/stories/Login/LoginContainer.tsx
storybook/stories/Logout/LogoutScreen.tsx
storybook/stories/mocks/navigation.tsx

[Notion link](https://www.notion.so/sally-wallet/Chore-Upgrade-Expo-SDK-to-45-storybook-linting-8f3445b37faf4ac2be8f5ddfaf51e364) 
- fix all storybook stories
- fix lint issue of possible undefined `products`
- fix env var issues (seems like after the update, we need to inject the env vars properly for each test)
- fix test issue in `LoginContainer` where domain format validation is failing (mock the regex validation)

chore: react-navigation v6 for storybook

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
.github/workflows/test_e2e.yml
package.json

[Notion link](https://www.notion.so/sally-wallet/05-Upgrade-Node-Version-for-SupplyAlly-app-mobile-application-86f0be6fb45d4abebbc94c870b8b037d) 
This PR upgrades node for volta and github workflows

chore: upgrade node

---

.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
.github/workflows/test_e2e.yml
package.json

Reverts rationally-app/mobile-application#651

chore: revert upgrade node

---

README.md
src/components/Layout/DrawerNavigation.tsx

[Notion link](https://www.notion.so/sally-wallet/07-Set-up-EAS-build-for-staging-and-prod-8c50e716f11a48edbc4606c8dbe62415) 
This PR fixes version not showing here

fix: version not showing

---

.github/scripts/create-profile.sh
.github/workflows/deploy_and_build_prod.yml

fix: prod pipeline typos

---

.github/workflows/deploy_and_build_prod.yml

fix: prod pipeline

---

package-lock.json
package.json

[Notion link](https://www.notion.so/sally-wallet/Remove-max-25-character-check-for-SGQR-Merchant-Name-7d551525e66c47c39184534d1fd790be) 
This PR updates the payment qr parser to 4.2.2 for mobile application, so that we can remove the max 25 character check for the SGQR merchant name. 
Recreating this PR because #627 is too old

chore(deps): bump payment-qr-parser to 4.2.2

---

package-lock.json
package.json

Reverts rationally-app/mobile-application#693 because the tests are still not passing

chore: revert "chore(deps): bump payment-qr-parser to 4.2.2"

---

package-lock.json
package.json

[Notion link](https://www.notion.so/sally-wallet/05-Tech-Spike-Patch-library-for-sally-mobile-app-bb62072bd532480e9b2cdc138c1ddd7b?pvs=4) 

chore: revert expo

---

package-lock.json
package.json

[Notion link](https://www.notion.so/sally-wallet/05-Tech-Spike-Patch-library-for-sally-mobile-app-bb62072bd532480e9b2cdc138c1ddd7b?pvs=4) 

chore: revert reanimate

---

.github/workflows/build_branch_preview.yml
.github/workflows/build_staging.yml
.github/workflows/deploy_and_build_prod.yml
.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_e2e.yml

[Notion link](https://www.notion.so/sally-wallet/Refactor-Deprecated-Github-Actions-99d665db11a44bb29261d11ccc1e9c2b?pvs=4) 
Changed set-output for GITHUB_ENV
-   [x] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
-   [x] I've requested reviews from 1-2 reviewers

chore: remove set-output

---

package-lock.json
package.json

[Notion link](https://www.notion.so/sally-wallet/05-Upgrade-to-EXPO-SDK-46-from-SDK-45-096eed02adcc492eb5d9a86d57159fc4?pvs=4) 

chore: bump sentry version

---

.github/scripts/create-profile.sh

- attempts to fix prod build/deploy: https://github.com/rationally-app/mobile-application/actions/runs/5131476614/jobs/9231611613

chore: remove releaseChannel from prod eas.json

---

app.config.ts

[Notion link](https://www.notion.so/sally-wallet/targetSdkVersion-33-to-satisfy-Target-API-level-requirements-for-Google-Play-apps-56687ea2249548708cea4115a4c138e5?pvs=4) 

chore: bump android target sdk version [SGW-3773]

---

src/components/HelpModal/HelpModal.tsx

[Notion link](https://www.notion.so/sally-wallet/07-GovSupply-mobile-app-Redirect-Need-help-Help-Support-from-Zendesk-to-Isomer-landing-si-e964496535d74e4b99efb6df6a1742ba) 
- new support URL in mobile app

chore: use landing page support url [SGW-3844]

---

.github/workflows/build_branch_preview.yml
.github/workflows/build_staging.yml
.github/workflows/deploy_and_build_prod.yml
.github/workflows/deploy_branch_preview.yml
.github/workflows/deploy_staging.yml
.github/workflows/test_development_environment.yml
.github/workflows/test_e2e.yml

chore(deps): update actions/setup-node action to v4

---

package-lock.json

```wrap
mobile-application on  master via  v16.17.0 took 2s 
❯ npm audit    
@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse
word-wrap  <1.2.4
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap
```

chore: ran npm audit fix

---

src/components/HelpModal/HelpModal.tsx
src/components/Layout/DrawerNavigation.tsx

[Notion link](https://www.notion.so/sally-wallet/07-GovSupply-mobile-app-Redirect-Need-help-Help-Support-from-Zendesk-to-Isomer-landing-si-e964496535d74e4b99efb6df6a1742ba?d=67ec4aa6290f4de3a7f186236cedbcd3) 
- updated GovSupply url

chore: update Supply URL [SGW-3844]

---

src/components/HelpModal/HelpModal.tsx

[Notion link](https://www.notion.so/sally-wallet/GovSupply-s-App-Ask-a-question-Webapp-s-Help-Support-Link-to-govsupply_support-tech-gov-sg-a652da071d504e13a8b7ce4a2eda5118) 
- update GS support email 
-   [ ] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
-   [ ] I've requested reviews from 1-2 reviewers
-   [ ] I've added/updated unit tests
-   [ ] I've added/updated e2e tests
-   [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

chore: update GovSupply support email [SGW-4160]

---

src/components/Login/utils.test.tsx
src/components/Login/utils.ts

Reverts rationally-app/mobile-application#777

chore: Revert "chore: updated the QR parser to be able to parse new format [SGW-4296]"

---

src/services/auth/index.tsx
src/services/quota/index.tsx

[Notion link](https://www.notion.so/sally-wallet/Track-GovSupply-Mobile-Application-usage-Stage-2-only-ff6f5097951b44ae85123a9fea34a820) 
- info log of check quota and get otp

chore: sentry info logs - to track mobile app usage [SGW-4520]
